TRUNCATE TABLE public.medications CASCADE;

DROP POLICY IF EXISTS "Enable insert access for all users" ON public.medications;
CREATE POLICY "Enable insert access for all users" ON public.medications FOR INSERT WITH CHECK (true);

INSERT INTO public.medications (source_type, reference_code, generic_name, trade_name, dosage_form, manufacturer, status) VALUES
('TMT', '336231', 'นิด้า ฟาร์มา', 'GLIPIZIDE-NIDA', '(glipizide 5 mg) tablet, 1 tablet', 'นิด้า ฟาร์มา', 'ACTIVE'),
('TMT', '768341', 'ไทยโอซูก้า', 'SODIUM CHLORIDE IRRIGATION U.S.P.', '(sodium chloride 900 mg/100 mL) irrigation solution, 1 L bottle', 'ไทยโอซูก้า', 'ACTIVE'),
('TMT', '103903', 'ยูนีซัน', 'FAMOMED 20', '(famotidine 20 mg) film-coated tablet, 1 tablet', 'ยูนีซัน', 'ACTIVE'),
('TMT', '150660', 'LEMERY, MEXICO', 'VIESSIA', '(vinorelbine 10 mg/1 mL) concentrate for solution for infusion, 1 mL vial', 'LEMERY, MEXICO', 'ACTIVE'),
('TMT', '613562', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'M-NADIN', '(ammonium chloride 125 mg/5 mL + diphenhydramine hydrochloride 12.5 mg/5 mL + sodium citrate dihydra', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '270877', 'KOREA PHARMA, KOREA', 'CALCITAROL SOFT CAP', '(calcitriol 0.25 mcg) capsule, soft, 1 capsule', 'KOREA PHARMA, KOREA', 'ACTIVE'),
('TMT', '856052', 'ฟาร์ม่า (ไทย', 'OLIVE OIL', ') (olive oil) cutaneous liquid, 450 mL bottle', 'ฟาร์ม่า (ไทย)', 'ACTIVE'),
('TMT', '363731', 'เวสโก ฟาร์มาซูติคอล', 'LORETIC', '(amiloride hydrochloride 5 mg + hydrochlorothiazide 50 mg) tablet, 1 tablet', 'เวสโก ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '128711', 'SANCHO, JAPAN', 'LOXONIN', '(loxoprofen 60 mg) tablet, 1 tablet', 'SANCHO, JAPAN', 'ACTIVE'),
('TMT', '954632', 'โปลิฟาร์ม', 'OSSIUM', '(ossein-hydroxyapatite compound 200 mg) coated tablet, 1 tablet', 'โปลิฟาร์ม', 'ACTIVE'),
('TMT', '816195', 'NON-ALCOHOL', 'PARACETAMOL', '(เภสัชกรรมทหาร) (paracetamol 120 mg/5 mL) syrup, 60 mL bottle', 'เภสัชกรรมทหาร', 'ACTIVE'),
('TMT', '745365', 'โมเดิร์น ฟาร์มา', 'OMEZOLE', '(omeprazole 20 mg) gastro-resistant capsule, hard, 1 capsule', 'โมเดิร์น ฟาร์มา', 'ACTIVE'),
('TMT', '947094', 'MICRO LABS, INDIA', 'NEVIRAPINE', '(nevirapine 200 mg) tablet, 1 tablet', 'MICRO LABS, INDIA', 'ACTIVE'),
('TMT', '848759', 'ศรีจันทร์สหโอสถ', 'PURE OLIVE OIL', '(olive oil) cutaneous liquid, 450 mL bottle', 'ศรีจันทร์สหโอสถ', 'ACTIVE'),
('TMT', '349412', 'ALZA, U.S.A.', 'INVEGA', '(paliperidone 3 mg) prolonged-release tablet, 1 tablet', 'ALZA, U.S.A.', 'ACTIVE'),
('TMT', '478788', 'WHITE', 'XEBRAMOL 325', '(เมดิซีน โปรดักส์) (paracetamol 325 mg) tablet, 1 tablet', 'เมดิซีน โปรดักส์', 'ACTIVE'),
('TMT', '595966', 'ชาญกิจเทรดดิ้ง', 'TRIPLE DROPS', '(brompheniramine maleate 2 mg/5 mL + phenylephrine hydrochloride 2.5 mg/5 mL) oral drops, solution, ', 'ชาญกิจเทรดดิ้ง', 'ACTIVE'),
('TMT', '782791', 'สยามเภสัช', 'BESANTA 300', '(irbesartan 300 mg) film-coated tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '790864', 'สยามเภสัช', 'VIFAS', '(fexofenadine hydrochloride 60 mg) film-coated tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '805574', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'DOPAMINE HYDROCHLORIDE', '(dopamine hydrochloride 50 mg/1 mL) concentrate for solution for infusion, 5 mL ampoule', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '960319', 'ORANGE', 'MINRA', '(ไทยนครพัฒนา) (brompheniramine maleate 2 mg/5 mL + phenylephrine hydrochloride 5 mg/5 mL) syrup, 60 ', 'ไทยนครพัฒนา', 'ACTIVE'),
('TMT', '1186993', 'อินแพคฟาร์มา', 'NORPAC 400', '(norfloxacin 400 mg) film-coated tablet, 1 tablet', 'อินแพคฟาร์มา', 'ACTIVE'),
('TMT', '590760', 'เกร๊ทเตอร์ฟาร์ม่า', 'GREATCILLIN', '(ampicillin 125 mg/5 mL) powder for syrup, 60 mL bottle', 'เกร๊ทเตอร์ฟาร์ม่า', 'ACTIVE'),
('TMT', '872331', '2 เอ็ม (เมด-เมเกอร์', 'T-ORA PASTE', ') (triamcinolone acetonide 100 mg/100 g) oromucosal paste, 1 g sachet', '2 เอ็ม (เมด-เมเกอร์)', 'ACTIVE'),
('TMT', '444875', 'ยูโทเปี้ยน', 'SOBERA', '(flunarizine 5 mg) tablet, 1 tablet', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '310229', 'บี.เจ. (เบญจโอสถ', 'DIAZEPAM 10', ') (diazepam 10 mg) tablet, 1 tablet', 'บี.เจ. (เบญจโอสถ)', 'ACTIVE'),
('TMT', '120236', 'Y F CHEMICAL, TAIWAN', 'CLOFON', '(diclofenac sodium 75 mg/3 mL) solution for injection, 3 mL ampoule', 'Y F CHEMICAL, TAIWAN', 'ACTIVE'),
('TMT', '906823', 'เบสซี่แอรอน', 'DECOLTAB', '(chlorphenamine maleate 2 mg + paracetamol 500 mg) tablet, 1 tablet', 'เบสซี่แอรอน', 'ACTIVE'),
('TMT', '368835', 'มิลลิเมด', 'MCXY PAR', '(paracetamol 500 mg) tablet, 1 tablet', 'มิลลิเมด', 'ACTIVE'),
('TMT', '102952', 'แอล.บี.เอส. แลบบอเรตอรี่', 'PANTIDINE', '(cimetidine 200 mg/2 mL) solution for injection, 2 mL ampoule', 'แอล.บี.เอส. แลบบอเรตอรี่', 'ACTIVE'),
('TMT', '336190', 'สหแพทย์เภสัช', 'GLIPIZIDE', '(glipizide 5 mg) film-coated tablet, 1 tablet', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '681624', 'BAYER OY, FINLAND', 'JADELLE', '(levonorgestrel 75 mg) implant, 1 implant', 'BAYER OY, FINLAND', 'ACTIVE'),
('TMT', '466855', 'CILAG, SWITZERLAND', 'ULTRACET', '(paracetamol 325 mg + tramadol hydrochloride 37.5 mg) film-coated tablet, 1 tablet', 'CILAG, SWITZERLAND', 'ACTIVE'),
('TMT', '376393', 'เอ.เอ็น.เอช. โปรดัคส์', 'METRONIDAZOLE', '(metronidazole 200 mg) tablet, 1 tablet', 'เอ.เอ็น.เอช. โปรดัคส์', 'ACTIVE'),
('TMT', '149639', 'TAE-JOON PHARM, KOREA', 'MOXAFEN', '(tamoxifen 20 mg) tablet, 1 tablet', 'TAE-JOON PHARM, KOREA', 'ACTIVE'),
('TMT', '126187', 'ชินต้าเทรดดิ้ง', 'BRUGIN JUNIOR', '(ibuprofen 100 mg/5 mL) oral suspension, 60 mL bottle', 'ชินต้าเทรดดิ้ง', 'ACTIVE'),
('TMT', '230225', 'ยูเมด้า', 'ACTIL', '(pseudoephedrine hydrochloride 60 mg + triprolidine hydrochloride 2.5 mg) tablet, 1 tablet (invalid)', 'ยูเมด้า', 'ACTIVE'),
('TMT', '941600', 'F 10676', 'SMW NO ALCOHOL', '(chlorhexidine 200 mg/100 mL) gargle/mouthwash, 450 mL bottle', 'โรงพยาบาลพุทธชินราช พิษณุโลก', 'ACTIVE'),
('TMT', '924602', 'F 13780', 'SALICYLIC 40% OINTMENT', '(salicylic acid 40 g/100 g) ointment, 30 g jar', 'โรงพยาบาลมหาราชนครเชียงใหม่', 'ACTIVE'),
('TMT', '388096', 'PATHEON, CANADA', 'NEOTIGASON', '(acitretin 25 mg) capsule, hard, 1 capsule', 'PATHEON, CANADA', 'ACTIVE'),
('TMT', '106473', 'ยูเมด้า', 'RANIN-25', '(ranitidine 50 mg/2 mL) solution for injection, 2 mL ampoule', 'ยูเมด้า', 'ACTIVE'),
('TMT', '718345', 'STERLING DRUG, MALAYSIA', 'DEQUADIN', '(dequalinium chloride 250 mcg) lozenge, 1 lozenge', 'STERLING DRUG, MALAYSIA', 'ACTIVE'),
('TMT', '394085', 'เลิศสิงห์เภสัชกรรม', 'NORMED 400', '(norfloxacin 400 mg) film-coated tablet, 1 tablet', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '844986', 'ไทยโอซูก้า', '5% DEXTROSE AND 0.3% SODIUM CHORIDE U.S.P. D-5-1/3 S', '(dextrose 5 g/100 mL + sodium chloride 300 mg/100 mL) solution for infusion, 500 mL bag', 'ไทยโอซูก้า', 'ACTIVE'),
('TMT', '417610', 'ที.แมน ฟาร์มา', 'PRIMET', '(trimethoprim 100 mg) film-coated tablet, 1 tablet', 'ที.แมน ฟาร์มา', 'ACTIVE'),
('TMT', '478994', 'แลชแมน', 'XETENEZAC', '(fluoxetine 20 mg) capsule, hard, 1 capsule', 'แลชแมน', 'ACTIVE'),
('TMT', '1343529', 'M 10819', 'PROPRANOLOL SUSPENSION', '(propranolol 1 mg/1 mL) oral suspension, 60 mL bottle', 'โรงพยาบาลบางละมุง', 'ACTIVE'),
('TMT', '806951', 'GLAXOSMITHKLINE, AUSTRALIA', 'FLIXOTIDE NEBULES', '(fluticasone propionate 500 mcg/2 mL) nebuliser suspension, 2 mL unit dose', 'GLAXOSMITHKLINE, AUSTRALIA', 'ACTIVE'),
('TMT', '418978', 'แลชแมน', 'PRONETINE-20', '(fluoxetine 20 mg) capsule, hard, 1 capsule', 'แลชแมน', 'ACTIVE'),
('TMT', '641487', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'TRIOFED', '(pseudoephedrine hydrochloride 30 mg/5 mL + triprolidine hydrochloride 1.25 mg/5 mL) syrup, 4 L gall', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '649968', 'MADAUS GMBH, GERMANY', 'SPASMO-LYT', '(trospium chloride 20 mg) coated tablet, 1 tablet', 'MADAUS GMBH, GERMANY', 'ACTIVE'),
('TMT', '836964', 'ที.โอ. เคมีคอลส์ (1979', 'CINNARIZINE', '(ปทุมธานี)) (cinnarizine 25 mg) tablet, 1 tablet', 'ที.โอ. เคมีคอลส์ (1979) (ปทุมธานี)', 'ACTIVE'),
('TMT', '999211', 'M 10747', 'ALLOPURINOL', '(allopurinol 10 mg/1 mL) oral suspension, 50 mL bottle', 'โรงพยาบาลพัทลุง', 'ACTIVE'),
('TMT', '410285', 'พาตาร์แลบ', 'PHENYTIN', '(phenytoin sodium 100 mg) capsule, hard, 1 capsule', 'พาตาร์แลบ', 'ACTIVE'),
('TMT', '131878', 'อาร์.พี.ซี. อินเตอร์เนชั่นแนล', 'TOPXEN', '(naproxen 250 mg) tablet, 1 tablet', 'อาร์.พี.ซี. อินเตอร์เนชั่นแนล', 'ACTIVE'),
('TMT', '384257', 'เวสโก ฟาร์มาซูติคอล', 'MUTEC', '(ambroxol hydrochloride 30 mg) tablet, 1 tablet', 'เวสโก ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '1167655', 'แมคโครฟาร์', 'MACROPECT', '(codeine phosphate 10 mg + guaifenesin 100 mg) capsule, soft, 1 capsule', 'แมคโครฟาร์', 'ACTIVE'),
('TMT', '898241', 'F 10670', 'SA 10% IN TA CREAM', '(salicylic acid 10 mg/100 mg + triamcinolone acetonide 100 mcg/100 mg) cream, 10 g tube', 'โรงพยาบาลขอนแก่น', 'ACTIVE'),
('TMT', '377002', 'ไบร์วู๊ดฟาร์มาซูติคอล', 'MEZOLE', '(metronidazole 250 mg) capsule, hard, 1 capsule', 'ไบร์วู๊ดฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '115386', 'P.T. PRIMA HEXAL, INDONESIA', 'FENOHEXAL 100', '(fenofibrate 100 mg) capsule, hard, 1 capsule', 'P.T. PRIMA HEXAL, INDONESIA', 'ACTIVE'),
('TMT', '108222', 'SLOVAKOFARMA, SLOVAKIA', 'WARFARIN 3-SL', '(warfarin sodium 3 mg) tablet, 1 tablet', 'SLOVAKOFARMA, SLOVAKIA', 'ACTIVE'),
('TMT', '129387', 'ห้างขายยาตราเจ็ดดาว', 'MENAGESIC', '(mefenamic acid 500 mg) film-coated tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '130779', 'สหการโอสถ', 'PAMIC 250', '(mefenamic acid 250 mg) capsule, hard, 1 capsule', 'สหการโอสถ', 'ACTIVE'),
('TMT', '1212261', 'มิลลิเมด บีเอฟเอส (เชียงราย', 'CHLOVAS-ZIS 40', ') (atorvastatin 40 mg) film-coated tablet, 1 tablet', 'มิลลิเมด บีเอฟเอส (เชียงราย)', 'ACTIVE'),
('TMT', '793327', 'KERN PHARMA, SPAIN', 'APO-GO', '(apomorphine hydrochloride 50 mg/5 mL) solution for injection, 5 mL ampoule', 'KERN PHARMA, SPAIN', 'ACTIVE'),
('TMT', '592910', 'แหลมทองการแพทย์', 'MANOVON', '(bromhexine hydrochloride 4 mg/5 mL) syrup, 100 mL bottle', 'แหลมทองการแพทย์', 'ACTIVE'),
('TMT', '982587', 'F 13781', 'WHITE 5', '(tranexamic acid 5 g/100 g) cream, 10 g jar', 'โรงพยาบาลรามาธิบดี', 'ACTIVE'),
('TMT', '124416', 'สยามเมดิแคร์', 'SABROFEN-400', '(ibuprofen 400 mg) film-coated tablet, 1 tablet', 'สยามเมดิแคร์', 'ACTIVE'),
('TMT', '371560', 'พี.พี. แลบอราตอรี่ส์', 'MED-MYOLAX', '(orphenadrine citrate 30 mg + paracetamol 500 mg) tablet, 1 tablet', 'พี.พี. แลบอราตอรี่ส์', 'ACTIVE'),
('TMT', '588835', 'พอนด์ เคมีคอล', 'MOXIL', '(amoxicillin 125 mg/5 mL) powder for oral suspension, 60 mL bottle', 'พอนด์ เคมีคอล', 'ACTIVE'),
('TMT', '575075', 'พี.พี. แลบอราตอรี่ส์', 'K.P.', '(phytomenadione 10 mg/1 mL) suspension for injection, 1 mL ampoule', 'พี.พี. แลบอราตอรี่ส์', 'ACTIVE'),
('TMT', '926967', 'F 12249', 'TCA 30% SOLUTION', '(trichloroacetic acid 30 g/100 mL) cutaneous solution, 30 mL bottle', 'สถาบันโรคผิวหนัง', 'ACTIVE'),
('TMT', '697458', 'ที.พี. ดรัก แลบบอราทอรี่ส์ (พระราม 2', 'PARACETAMOL', ') (paracetamol 500 mg) tablet, 1 tablet', 'ที.พี. ดรัก แลบบอราทอรี่ส์ (พระราม 2)', 'ACTIVE'),
('TMT', '126909', 'ยูเมด้า', 'UMAFEN SUSPENSION', '(ibuprofen 100 mg/5 mL) oral suspension, 60 mL bottle', 'ยูเมด้า', 'ACTIVE'),
('TMT', '411653', 'เพรซิเดนท์ อินเตอร์ ฟาร์มา', 'PIPMINOX 5', '(minoxidil 5 mg) tablet, 1 tablet', 'เพรซิเดนท์ อินเตอร์ ฟาร์มา', 'ACTIVE'),
('TMT', '125502', 'เอช.เค.ฟาร์มาซูติคอล', 'IBUPROFEN 400', '(ibuprofen 400 mg) film-coated tablet, 1 tablet', 'เอช.เค.ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '136217', 'ไทยนครพัฒนา', 'NOXICAM', '(tenoxicam 20 mg) tablet, 1 tablet', 'ไทยนครพัฒนา', 'ACTIVE'),
('TMT', '576167', 'CHEMISCHE FABRIK KREUSSLER, GERMANY', 'AETHOXYSKLEROL', '(lauromacrogol 400 3 g/100 mL) solution for injection, 2 mL ampoule', 'CHEMISCHE FABRIK KREUSSLER, GERMANY', 'ACTIVE'),
('TMT', '921695', 'F 12249', 'LACTIC ACID 5% CREAM', '(lactic acid 5 g/100 g) cream, 30 g jar', 'สถาบันโรคผิวหนัง', 'ACTIVE'),
('TMT', '234950', 'ห้างขายยาตราเจ็ดดาว', 'ALLO 100', '(allopurinol 100 mg) tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '1153551', 'M 10723', 'ACETAZOLAMIDE', '(acetazolamide 10 mg/1 mL) oral suspension, 50 mL bottle', 'โรงพยาบาลแม่สอด', 'ACTIVE'),
('TMT', '446911', 'ORION CORPORATION, FINLAND', 'STALEVO', '(carbidopa 25 mg + entacapone 200 mg + levodopa 100 mg) film-coated tablet, 1 tablet', 'ORION CORPORATION, FINLAND', 'ACTIVE'),
('TMT', '1219489', '10 MG TABLET', 'MEMOTIN', '(แอตแลนติค) (memantine hydrochloride 10 mg) film-coated tablet, 1 tablet', 'แอตแลนติค', 'ACTIVE'),
('TMT', '872417', '2 เอ็ม (เมด-เมเกอร์', 'PISALIN', ') (chloramphenicol 1 g/100 g) ointment, 15 g tube', '2 เอ็ม (เมด-เมเกอร์)', 'ACTIVE'),
('TMT', '118272', 'ที.โอ. ฟาร์ม่า', 'DICLOFENAC', '(diclofenac sodium 25 mg) film-coated tablet, 1 tablet', 'ที.โอ. ฟาร์ม่า', 'ACTIVE'),
('TMT', '396641', 'นิวยอร์ค เคมีเกิ้ล', 'NYMUSOV', '(ambroxol hydrochloride 30 mg) tablet, 1 tablet', 'นิวยอร์ค เคมีเกิ้ล', 'ACTIVE'),
('TMT', '938550', 'F 10679', 'SYRUP FOR OSELTAMIVIR', '(sucrose 80 g/100 mL) syrup, 60 mL bottle', 'โรงพยาบาลนครปฐม', 'ACTIVE'),
('TMT', '491838', 'LEO PHARMACEUTICAL PRODUCTS, DENMARK', 'DAIVONEX', '(calcipotriol 5 mg/100 mL) cutaneous solution, 30 mL bottle', 'LEO PHARMACEUTICAL PRODUCTS, DENMARK', 'ACTIVE'),
('TMT', '588596', 'สหแพทย์เภสัช', 'MOC-C', '(amoxicillin 125 mg/5 mL) powder for oral suspension, 60 mL bottle', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '430546', 'พิคโก้ฟาร์มา', 'RIPIN', '(rifampicin 300 mg) capsule, hard, 1 capsule', 'พิคโก้ฟาร์มา', 'ACTIVE'),
('TMT', '243499', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'AMPICILLIN', '(ampicillin 500 mg) capsule, hard, 1 capsule', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'ACTIVE'),
('TMT', '937253', 'F 10733', 'CHLORAL HYDRATE SYRUP', '(chloral hydrate 10 g/100 mL) syrup, 60 mL bottle', 'โรงพยาบาลสมเด็จพระสังฆราช องค์ที่ 17', 'ACTIVE'),
('TMT', '478412', 'ไฟเซอร์', 'XANAX', '(alprazolam 250 mcg) tablet, 1 tablet', 'ไฟเซอร์', 'ACTIVE'),
('TMT', '689744', 'องค์การเภสัชกรรม', 'CHLORPHENIRAMINE', '(chlorphenamine maleate 4 mg) tablet, 1 tablet', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '513994', 'ที.โอ. เคมีคอลส์ (1979', 'MUPORIN', '(กรุงเทพฯ)) (mupirocin 2 g/100 g) ointment, 100 g tube', 'ที.โอ. เคมีคอลส์ (1979) (กรุงเทพฯ)', 'ACTIVE'),
('TMT', '907928', 'SWISS CAPS LOHNHERSTELLUNGS, SWITZERLAND', 'IMUVIT', '(minerals + multivitamins) capsule, soft, 1 capsule', 'SWISS CAPS LOHNHERSTELLUNGS, SWITZERLAND', 'ACTIVE'),
('TMT', '1019499', 'บูรพาโอสถ', 'B.P. CORT', '(triamcinolone acetonide 20 mg/100 g) cream, 500 g jar', 'บูรพาโอสถ', 'ACTIVE'),
('TMT', '556157', 'ที.พี. ดรัก แลบบอราทอรี่ส์', 'DEXTON', '(dexamethasone 4 mg/1 mL) powder for solution for injection, 10 mL vial', 'ที.พี. ดรัก แลบบอราทอรี่ส์', 'ACTIVE'),
('TMT', '711606', 'HOSPITAL FORMULARY', 'COLONIC LAVAGE', '(colonic lavage) oral powder (invalid)', 'HOSPITAL FORMULARY', 'ACTIVE'),
('TMT', '887255', 'INTAS PHARMACEUTICALS, INDIA', 'DOTAX', '(docetaxel 20 mg/0.5 mL) concentrate and solvent for solution for infusion, 0.5 mL vial', 'INTAS PHARMACEUTICALS, INDIA', 'ACTIVE'),
('TMT', '898740', 'F 10670', 'TA 0.02% CREAM', '(triamcinolone acetonide 20 mg/100 g) cream, 90 g tube', 'โรงพยาบาลขอนแก่น', 'ACTIVE'),
('TMT', '546978', 'HIKMA FARMACEUTICA, PORTUGAL', 'TOTAM', '(cefotaxime 500 mg) powder for solution for injection/infusion, 1 vial', 'HIKMA FARMACEUTICA, PORTUGAL', 'ACTIVE'),
('TMT', '453817', 'เภสัชกรรมนครพัฒนา', 'TEMACO', '(theophylline 125 mg) tablet, 1 tablet', 'เภสัชกรรมนครพัฒนา', 'ACTIVE'),
('TMT', '481188', 'BRISTOL-MYERS SQUIBB MANUFACTURING, U.S.A.', 'ZERIT', '(stavudine 15 mg) capsule, hard, 1 capsule', 'BRISTOL-MYERS SQUIBB MANUFACTURING, U.S.A.', 'ACTIVE'),
('TMT', '480063', 'สยามเภสัช', 'ZEBEN', '(albendazole 200 mg) film-coated tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '121917', 'บางกอกแล็ป แอนด์ คอสเมติค', 'GLUCOSA-J 1500 POWDER', '(glucosamine sulfate 1.5 g/3.95 g) powder for oral solution, 3.95 g sachet', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '353342', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'KATRAX', '(hydroxyzine hydrochloride 10 mg) tablet, 1 tablet', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '668036', 'SANOFI-AVENTIS, GERMANY', 'INSUMAN COMB 25', '(insulin human 25 iu/1 mL + isophane insulin 75 iu/1 mL) suspension for injection, 3 mL cartridge', 'SANOFI-AVENTIS, GERMANY', 'ACTIVE'),
('TMT', '440508', 'GLAXOSMITHKLINE, CANADA', 'SEROXAT CR', '(paroxetine 25 mg) film-coated tablet, 1 tablet', 'GLAXOSMITHKLINE, CANADA', 'ACTIVE'),
('TMT', '104778', 'ห้างขายยาตราเจ็ดดาว', 'OMESTAR', '(omeprazole 20 mg) gastro-resistant capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '877729', '2 เอ็ม (เมด-เมเกอร์', 'ACCIN 2', ') (tretinoin 50 mg/100 g) cream, 5 g tube', '2 เอ็ม (เมด-เมเกอร์)', 'ACTIVE'),
('TMT', '434136', 'อาร์.พี.ซี. อินเตอร์เนชั่นแนล', 'ROXONE', '(roxithromycin 150 mg) film-coated tablet, 1 tablet', 'อาร์.พี.ซี. อินเตอร์เนชั่นแนล', 'ACTIVE'),
('TMT', '346206', 'ที.แมน ฟาร์มา', 'HYDROX-10', '(hydroxyzine hydrochloride 10 mg) film-coated tablet, 1 tablet', 'ที.แมน ฟาร์มา', 'ACTIVE'),
('TMT', '116011', 'สยามเภสัช', 'GEMFIBRIL OD', '(gemfibrozil 900 mg) film-coated tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '387003', 'LES LABORATOIRES SERVIER, FRANCE', 'NATRILIX SR', '(indapamide 1.5 mg) prolonged-release tablet, 1 tablet', 'LES LABORATOIRES SERVIER, FRANCE', 'ACTIVE'),
('TMT', '738042', 'เบสซี่แอรอน', 'PANATE', '(lithium carbonate 300 mg) capsule, hard, 1 capsule', 'เบสซี่แอรอน', 'ACTIVE'),
('TMT', '428633', 'วี.เอส. ฟาร์ม่า (1971', 'RIFAM V-300', ') (rifampicin 300 mg) capsule, hard, 1 capsule', 'วี.เอส. ฟาร์ม่า (1971)', 'ACTIVE'),
('TMT', '769070', 'GLAXOSMITHKLINE MANUFACTURING, ITALY', 'TRACRIUM', '(atracurium besilate 50 mg/5 mL) solution for injection/infusion, 5 mL ampoule', 'GLAXOSMITHKLINE MANUFACTURING, ITALY', 'ACTIVE'),
('TMT', '137268', 'สยามเภสัช', 'ULSANIC', '(sucralfate 1 g/5 mL) oral suspension, 5 mL sachet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '452617', 'วี.แอนด์.พี ลาบอราตอรี่', 'TANYA', '(chlorphenamine maleate 2 mg + paracetamol 325 mg + pseudoephedrine hydrochloride 30 mg) tablet, 1 t', 'วี.แอนด์.พี ลาบอราตอรี่', 'ACTIVE'),
('TMT', '873405', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'ERYTHROMYCIN ESTOLATE', '(erythromycin 250 mg) capsule, hard, 1 capsule', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'ACTIVE'),
('TMT', '238039', 'ยูโทเปี้ยน', 'AMBUTOL', '(ethambutol hydrochloride 400 mg) film-coated tablet, 1 tablet', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '1112809', 'ห้างขายยาตราเจ็ดดาว', 'TRANEX-STAR', '(tranexamic acid 250 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '851848', 'ASTRAZENECA PHARMACEUTICAL, U.S.A.', 'FORXIGA', '(dapagliflozin 10 mg) film-coated tablet, 1 tablet', 'ASTRAZENECA PHARMACEUTICAL, U.S.A.', 'ACTIVE'),
('TMT', '805087', 'RECKITT BENCKISER HEALTHCARE, U.K.', 'DETTOL ANTISEPTIC CREAM', '(chloroxylenol 300 mg/100 g + edetic acid 200 mg/100 g + triclosan 300 mg/100 g) cream, 30 g tube', 'RECKITT BENCKISER HEALTHCARE, U.K.', 'ACTIVE'),
('TMT', '814259', 'BAYER PHARMA, GERMANY', 'GADOVIST', '(gadobutrol 1 mmol/1 mL) solution for injection, 15 mL vial', 'BAYER PHARMA, GERMANY', 'ACTIVE'),
('TMT', '469276', 'PIETTE LABORATORISES INTERNATIONAL, BELGIUM', 'UTROGESTAN', '(progesterone 100 mg) capsule, soft, 1 capsule', 'PIETTE LABORATORISES INTERNATIONAL, BELGIUM', 'ACTIVE'),
('TMT', '1133715', 'เอเบิ้ล เมดิคอล', 'D-5-S', '(dextrose 5 g/100 mL + sodium chloride 900 mg/100 mL) solution for infusion, 1 L bag', 'เอเบิ้ล เมดิคอล', 'ACTIVE'),
('TMT', '362634', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'LOPORIC', '(allopurinol 100 mg) tablet, 1 tablet', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '634891', 'เมดิซีน โปรดักส์', 'ANTOMOL', '(salbutamol 2 mg/5 mL) syrup, 60 mL bottle', 'เมดิซีน โปรดักส์', 'ACTIVE'),
('TMT', '1320549', 'BIONTECH MANUFACTURING, GERMANY', 'COMIRNATY', '(bretovameran 30 mcg/1 dose) dispersion for injection, 0.3 mL vial', 'BIONTECH MANUFACTURING, GERMANY', 'ACTIVE'),
('TMT', '328469', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'FLUDIZOL', '(fluconazole 50 mg) capsule, hard, 1 capsule', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '567783', 'EURO-MED LABORATORIES, PHILIPPINES', 'MANNITOL 20%', '(mannitol 20 g/100 mL) solution for infusion, 100 mL bag', 'EURO-MED LABORATORIES, PHILIPPINES', 'ACTIVE'),
('TMT', '675074', 'CILAG, SWITZERLAND', 'EPREX', '(epoetin alfa 40000 iu/1 mL) solution for injection, 1 mL prefilled syr (invalid)', 'CILAG, SWITZERLAND', 'ACTIVE'),
('TMT', '563415', 'YUNG SHIN PHARMACEUTICAL IND, TAIWAN', 'YUNGJIN', '(cilastatin 500 mg + imipenem 500 mg) powder for solution for infusion, 1 vial', 'YUNG SHIN PHARMACEUTICAL IND, TAIWAN', 'ACTIVE'),
('TMT', '506081', 'ดาเบอร์ ฟาร์มา', 'IODINE PAINT COMPOUND', '(iodine 1.25 g/100 mL + potassium iodide 2.5 g/100 mL) cutaneous solution, 450 mL bottle', 'ดาเบอร์ ฟาร์มา', 'ACTIVE'),
('TMT', '672000', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ZYNO', '(triamcinolone acetonide 100 mg/100 g) cream, 15 g tube', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '822689', '200/5', 'ZENHALE', '(3M HEALTH CARE, U.K.) (formoterol fumarate dihydrate 5 mcg/1 dose + mometasone furoate 200 mcg/1 do', '3M HEALTH CARE, U.K.', 'ACTIVE'),
('TMT', '1023556', 'F 10677', 'D-5-W', '(dextrose 5 g/100 mL) solution for infusion, 500 mL bottle', 'โรงพยาบาลราชบุรี', 'ACTIVE'),
('TMT', '115960', 'มิลลิเมด', 'MILPID-600', '(gemfibrozil 600 mg) film-coated tablet, 1 tablet', 'มิลลิเมด', 'ACTIVE'),
('TMT', '444538', 'แลชแมน', 'SITACIL-500', '(ampicillin 500 mg) capsule, hard, 1 capsule', 'แลชแมน', 'ACTIVE'),
('TMT', '1259884', 'REYON PHARMACEUTICAL, KOREA', 'ROCAINE INJECTION 7.5 MG/ML', '(ropivacaine hydrochloride 150 mg/20 mL) solution for injection, 20 mL ampoule', 'REYON PHARMACEUTICAL, KOREA', 'ACTIVE'),
('TMT', '275864', 'เคมีภัณฑ์ เมดิคอล', 'CELATAG', '(cetirizine hydrochloride 10 mg) tablet, 1 tablet', 'เคมีภัณฑ์ เมดิคอล', 'ACTIVE'),
('TMT', '377831', 'มิลาโน', 'MILANOX', '(amoxicillin 250 mg) capsule, hard, 1 capsule', 'มิลาโน', 'ACTIVE'),
('TMT', '882127', 'ยูโทเปี้ยน', 'UOSPAN', '(hyoscine butylbromide 10 mg) tablet, 1 tablet', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '749738', 'ASTRAZENECA, U.K.', 'IRESSA', '(gefitinib 250 mg) film-coated tablet, 1 tablet', 'ASTRAZENECA, U.K.', 'ACTIVE'),
('TMT', '281281', 'MAKERS LABORATORIES, INDIA', 'CHLOROQUINE PHOSPHATE TABLETS BP', '(chloroquine phosphate 250 mg) film-coated tablet, 1 tablet', 'MAKERS LABORATORIES, INDIA', 'ACTIVE'),
('TMT', '597388', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'FLEMEX', '(carbocisteine 250 mg/5 mL) syrup, 60 mL bottle', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '131558', 'โอลิค', 'NAPROSYN LE', '(naproxen 250 mg) tablet, 1 tablet', 'โอลิค', 'ACTIVE'),
('TMT', '336980', 'ที.โอ. เคมีคอลส์ (1979', 'GLUCOLYTE', '(กรุงเทพฯ)) (metformin hydrochloride 500 mg) film-coated tablet, 1 tablet', 'ที.โอ. เคมีคอลส์ (1979) (กรุงเทพฯ)', 'ACTIVE'),
('TMT', '998962', 'F 10747', 'JOULIE''S SOLUTION', '(dibasic sodium phosphate 539 mg/100 mL + monobasic potassium phosphate 1.3 g/100 mL) oral solution,', 'โรงพยาบาลพัทลุง', 'ACTIVE'),
('TMT', '126899', 'ที.พี. ดรัก แลบบอราทอรี่ส์', 'TROFEN', '(ibuprofen 100 mg/5 mL) oral suspension, 60 mL bottle', 'ที.พี. ดรัก แลบบอราทอรี่ส์', 'ACTIVE'),
('TMT', '432694', 'โรต้าลาบอเร็ทตอรี่ส์', 'ROTANOLOL', '(atenolol 50 mg) film-coated tablet, 1 tablet', 'โรต้าลาบอเร็ทตอรี่ส์', 'ACTIVE'),
('TMT', '894960', 'F 10677', 'D-50-S/2', '(dextrose 50 g/100 mL + sodium chloride 450 mg/100 mL) solution for infusion, 1 L bottle', 'โรงพยาบาลราชบุรี', 'ACTIVE'),
('TMT', '1201033', 'HAINAN POLY PHARM, CHINA', 'LEVETIRACETAM HAINAN POLY 100 MG/ML CONCENTRATE FOR SOLUTION FOR INFUSION', '(levetiracetam 500 mg/5 mL) concentrate for solution for infusion, 5 mL vial', 'HAINAN POLY PHARM, CHINA', 'ACTIVE'),
('TMT', '1016629', 'อินแพคฟาร์มา', 'BENZYL BENZOATE', '(benzyl benzoate 25 g/100 mL) cutaneous emulsion, 100 mL bottle', 'อินแพคฟาร์มา', 'ACTIVE'),
('TMT', '411258', 'วี.เอส. ฟาร์ม่า (1971', 'PINRIZINE', ') (cinnarizine 25 mg) tablet, 1 tablet', 'วี.เอส. ฟาร์ม่า (1971)', 'ACTIVE'),
('TMT', '1039031', 'HOE PHARMACEUTICALS, MALAYSIA', 'A SCALP', '(permethrin 1 g/100 mL) cutaneous emulsion, 60 mL bottle', 'HOE PHARMACEUTICALS, MALAYSIA', 'ACTIVE'),
('TMT', '462772', 'พอนด์ เคมีคอล', 'TREX-120', '(sulfamethoxazole 100 mg + trimethoprim 20 mg) coated tablet, 1 tablet', 'พอนด์ เคมีคอล', 'ACTIVE'),
('TMT', '1044093', 'มิลลิเมด', 'CYSTALINE', '(acetylcysteine 600 mg) effervescent powder, 3.1 g sachet', 'มิลลิเมด', 'ACTIVE'),
('TMT', '777875', 'MALLINCKRODT, U.S.A.', 'OPTIMARK', '(gadoversetamide 330.9 mg/1 mL) solution for injection, 15 mL prefilled syr', 'MALLINCKRODT, U.S.A.', 'ACTIVE'),
('TMT', '923992', 'F 10683', 'POTASSIUM CHLORIDE ELIXIR', '(potassium chloride 10 g/100 mL) oral solution, 30 mL bottle', 'โรงพยาบาลศูนย์ตรัง', 'ACTIVE'),
('TMT', '250054', 'เอเชี่ยนยูเนียนแล็บบอราตอรี่ส์', 'ASADEX', '(dextromethorphan hydrobromide 15 mg) tablet, 1 tablet', 'เอเชี่ยนยูเนียนแล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '891813', 'F 13755', 'THYMOL 3%', '(thymol 3 g/100 mL) cutaneous solution, 60 mL bottle', 'โรงพยาบาลโรคผิวหนังเขตร้อนภาคใต้ จังหวัดตรัง', 'ACTIVE'),
('TMT', '629925', 'เลิศสิงห์เภสัชกรรม', 'PARACETAMOL', '(paracetamol 120 mg/5 mL) syrup, 60 mL bottle', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '275523', 'RENATA, BANGLADESH', 'CEFTIL 500', '(cefuroxime 500 mg) film-coated tablet, 1 tablet', 'RENATA, BANGLADESH', 'ACTIVE'),
('TMT', '922563', 'F 13780', 'LIDOCAINE VISCOUS', '(lidocaine hydrochloride 2 g/100 mL) oromucosal solution, 30 mL bottle', 'โรงพยาบาลมหาราชนครเชียงใหม่', 'ACTIVE'),
('TMT', '509043', 'ที.โอ. เคมีคอลส์ (1979', 'NINAZOL', '(กรุงเทพฯ)) (ketoconazole 2 g/100 mL) shampoo, 100 mL bottle', 'ที.โอ. เคมีคอลส์ (1979) (กรุงเทพฯ)', 'ACTIVE'),
('TMT', '609337', 'สหการโอสถ', 'UNICOF KIDS', '(bromhexine hydrochloride 4 mg/5 mL + dextromethorphan hydrobromide 7.5 mg/5 mL) syrup, 60 mL bottle', 'สหการโอสถ', 'ACTIVE'),
('TMT', '421267', 'เอส.ที. กรุ๊ป ฟาร์ม่า', 'PYRIDOXINE HCL', '(pyridoxine hydrochloride 10 mg) tablet, 1 tablet', 'เอส.ที. กรุ๊ป ฟาร์ม่า', 'ACTIVE'),
('TMT', '948271', 'FRESENIUS KABI ONCOLOGY, INDIA', 'ANTHRACIN', '(epirubicin hydrochloride 50 mg/25 mL) solution for injection/infusion, 25 mL vial', 'FRESENIUS KABI ONCOLOGY, INDIA', 'ACTIVE'),
('TMT', '969803', 'F 13781', 'PSORIASIS OINTMENT 2', '(coal tar 10 g/100 g + salicylic acid 5 g/100 g) ointment, 30 g bottle', 'โรงพยาบาลรามาธิบดี', 'ACTIVE'),
('TMT', '1042672', 'เภสัชกรรม เค.บี.', 'K.B.TRIBEMIN', '(cyanocobalamin 50 mcg + pyridoxine hydrochloride 5 mg + thiamine 100 mg) tablet, 1 tablet', 'เภสัชกรรม เค.บี.', 'ACTIVE'),
('TMT', '147119', 'โอลัน-เคมเมด', 'DEPRORA', '(medroxyprogesterone acetate 150 mg/3 mL) suspension for injection, 3 mL vial', 'โอลัน-เคมเมด', 'ACTIVE'),
('TMT', '1264782', '10 MG', 'ZOLAN GPO', '(องค์การเภสัชกรรม) (olanzapine 10 mg) orodispersible tablet, 1 tablet', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '1030817', 'F 10731', 'MOM', '(magnesium hydroxide 425 mg/5 mL) oral suspension, 240 mL bottle', 'โรงพยาบาลพหลพลพยุหเสนา', 'ACTIVE'),
('TMT', '547182', 'ยูนีซัน', 'MAXOTIN', '(cefoxitin 1 g) powder for solution for injection, 1 vial', 'ยูนีซัน', 'ACTIVE'),
('TMT', '148355', 'PHARMACHEMIE, NETHERLANDS', 'OXALIPLATIN', '(oxaliplatin 5 mg/1 mL) solution for injection, 10 mL vial (invalid)', 'PHARMACHEMIE, NETHERLANDS', 'ACTIVE'),
('TMT', '454017', 'เมดิซีน โปรดักส์', 'TENAMED 50', '(atenolol 50 mg) film-coated tablet, 1 tablet', 'เมดิซีน โปรดักส์', 'ACTIVE'),
('TMT', '376372', 'แสงไทยกำปะนี', 'METRONIDAZOLE', '(metronidazole 200 mg) tablet, 1 tablet', 'แสงไทยกำปะนี', 'ACTIVE'),
('TMT', '354779', 'ยูโทเปี้ยน', 'KETOMED', '(ketoconazole 200 mg) tablet, 1 tablet', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '432057', 'สหแพทย์เภสัช', 'ROMED 300', '(roxithromycin 300 mg) film-coated tablet, 1 tablet', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '506774', 'เอส.เอ็ม. ฟาร์มาซูติคอล', 'KA-CILONE', '(kanamycin 500 mg/100 g + triamcinolone acetonide 100 mg/100 g) ointment, 5 g tube', 'เอส.เอ็ม. ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '470846', 'เบอร์ลินฟาร์มาซูติคอลอินดัสตรี้', 'VATOL', '(metoprolol tartrate 100 mg) tablet, 1 tablet', 'เบอร์ลินฟาร์มาซูติคอลอินดัสตรี้', 'ACTIVE'),
('TMT', '1052706', 'โปลิฟาร์ม', 'P-TOCORT', '(clobetasol propionate 50 mg/100 g) cream, 500 g jar', 'โปลิฟาร์ม', 'ACTIVE'),
('TMT', '147135', 'ยูเมด้า', 'ENAF-150', '(medroxyprogesterone acetate 150 mg/3 mL) suspension for injection, 3 mL vial', 'ยูเมด้า', 'ACTIVE'),
('TMT', '1163417', 'แหลมทองการแพทย์', 'THYROXINE', '(levothyroxine sodium 100 mcg) coated tablet, 1 tablet', 'แหลมทองการแพทย์', 'ACTIVE'),
('TMT', '1346201', '60 MG', 'WINREVAIR', '(PATHEON ITALIA, ITALY) (sotatercept 60 mg) powder and solvent for solution for injection, 1 vial', 'PATHEON ITALIA, ITALY', 'ACTIVE'),
('TMT', '1134830', 'ACTAVIS, MALTA', 'AREPRA 10', '(aripiprazole 10 mg) orodispersible tablet, 1 tablet', 'ACTAVIS, MALTA', 'ACTIVE'),
('TMT', '141875', 'HOSPIRA, AUSTRALIA', 'DBL FLUOROURACIL', '(fluorouracil 250 mg/5 mL) solution for injection/infusion, 5 mL vial', 'HOSPIRA, AUSTRALIA', 'ACTIVE'),
('TMT', '1015365', 'ZENTIVA, CZECH', 'ROSUGRIX', '(rosuvastatin 10 mg) film-coated tablet, 1 tablet', 'ZENTIVA, CZECH', 'ACTIVE'),
('TMT', '882638', 'F 10677', 'D-20-S/2', '(estradiol 1.5 mg + nomegestrol acetate 2.5 mg) film-coated tablet, 500 mL bottle (invalid)', 'โรงพยาบาลราชบุรี', 'ACTIVE'),
('TMT', '630628', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'PARAGEN', '(paracetamol 500 mg/5 mL) syrup, 60 mL bottle', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'ACTIVE'),
('TMT', '499084', 'ค็อกซ์', 'CLOTRI-B', '(betamethasone dipropionate 100 mg/100 g + clotrimazole 1 g/100 g) cream, 100 g tube', 'ค็อกซ์', 'ACTIVE'),
('TMT', '561155', 'SUN PHARMACEUTICAL, INDIA', 'CARDIJECT', '(dobutamine 250 mg/20 mL) concentrate for solution for infusion, 20 mL vial', 'SUN PHARMACEUTICAL, INDIA', 'ACTIVE'),
('TMT', '581558', 'HOSPIRA, AUSTRALIA', 'VANCOMCIN HYDROCHLORIDE U.S.P.', '(vancomycin 1 g) powder for solution for infusion, 1 vial', 'HOSPIRA, AUSTRALIA', 'ACTIVE'),
('TMT', '379657', 'เลิศสิงห์เภสัชกรรม', 'MODUMED', '(amiloride hydrochloride 2.5 mg + hydrochlorothiazide 25 mg + timolol 10 mg) tablet, 1 tablet', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '719011', 'AESICA PHARMACEUTICALS, GERMANY', 'TOVIAZ', '(fesoterodine fumarate 8 mg) prolonged-release tablet, 1 tablet', 'AESICA PHARMACEUTICALS, GERMANY', 'ACTIVE'),
('TMT', '542924', 'โอลิค', 'GLUCO-CALCIUM', '(calcium 18 mg/1 mL) solution for injection, 30 mL vial', 'โอลิค', 'ACTIVE'),
('TMT', '109682', 'ไบโอแลป', 'FELOTEN', '(felodipine 5 mg) prolonged-release tablet, 1 tablet', 'ไบโอแลป', 'ACTIVE'),
('TMT', '241579', 'ห้างขายยาตราเจ็ดดาว', 'AMOXY-250 COSMA', '(amoxicillin 250 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '727185', 'โรงงานเภสัชกรรมเกร๊ทเตอร์ฟาร์ม่า', 'ROXTROCIN 150', '(roxithromycin 150 mg) film-coated tablet, 1 tablet', 'โรงงานเภสัชกรรมเกร๊ทเตอร์ฟาร์ม่า', 'ACTIVE'),
('TMT', '613723', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'SANODRYL', '(ammonium chloride 125 mg/5 mL + diphenhydramine hydrochloride 12.5 mg/5 mL) syrup, 60 mL bottle', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'ACTIVE'),
('TMT', '260043', 'เฉลิมชัยเภสัช', 'BENACOL D', '(chlorphenamine maleate 4 mg + paracetamol 325 mg + phenylephrine hydrochloride 10 mg) capsule, hard', 'เฉลิมชัยเภสัช', 'ACTIVE'),
('TMT', '1299160', 'INTAS PHARMACEUTICALS, INDIA', 'FULEVEX', '(fulvestrant 250 mg/5 mL) solution for injection, 5 mL prefilled syr', 'INTAS PHARMACEUTICALS, INDIA', 'ACTIVE'),
('TMT', '261658', 'เบสซี่แอรอน', 'BESSOFED', '(pseudoephedrine hydrochloride 60 mg + triprolidine hydrochloride 2.5 mg) tablet, 1 tablet', 'เบสซี่แอรอน', 'ACTIVE'),
('TMT', '649437', 'ASTRAZENECA, U.K.', 'SEROQUEL', '(quetiapine 25 mg) film-coated tablet, 1 tablet', 'ASTRAZENECA, U.K.', 'ACTIVE'),
('TMT', '1281841', 'สหแพทย์เภสัช', 'DESLORA', '(desloratadine 5 mg) film-coated tablet, 1 tablet', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '531620', 'โอลิค', 'LOMOTIL', '(atropine sulfate 25 mcg + diphenoxylate hydrochloride 2.5 mg) tablet, 1 tablet', 'โอลิค', 'ACTIVE'),
('TMT', '109006', 'NOVARTIS PHARMA, SWITZERLAND', 'EXFORGE HCT', '(amlodipine 10 mg + hydrochlorothiazide 25 mg + valsartan 320 mg) film-coated tablet, 1 tablet (inva', 'NOVARTIS PHARMA, SWITZERLAND', 'ACTIVE'),
('TMT', '616611', 'นิวยอร์ค เคมีเกิ้ล', 'NYCARAX', '(hydroxyzine hydrochloride 10 mg/5 mL) syrup, 60 mL bottle', 'นิวยอร์ค เคมีเกิ้ล', 'ACTIVE'),
('TMT', '1163331', 'แหลมทองการแพทย์', 'THYROXINE', '(levothyroxine sodium 100 mcg) tablet, 1 tablet', 'แหลมทองการแพทย์', 'ACTIVE'),
('TMT', '869652', 'แอตแลนติค', 'BECOLIM FORTE', '(calcium pantothenate 5 mg + cyanocobalamin 1 mcg + nicotinamide 50 mg + pyridoxine 1 mg + riboflavi', 'แอตแลนติค', 'ACTIVE'),
('TMT', '1043575', 'สามัคคีเภสัช', 'CARBO-MINT', '(activated charcoal 65 mg + peppermint oil 1 mg + sodium bicarbonate 250 mg) tablet, 1 tablet', 'สามัคคีเภสัช', 'ACTIVE'),
('TMT', '1114557', 'B. BRAUN MEDICAL INDUSTRIES, MALAYSIA', '0.9% SODIUM CHLORIDE', '(sodium chloride 900 mg/100 mL) solution for infusion, 1 L bag', 'B. BRAUN MEDICAL INDUSTRIES, MALAYSIA', 'ACTIVE'),
('TMT', '116360', 'ห้างขายยาตราเจ็ดดาว', 'GEMFI STAR 300', '(gemfibrozil 300 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '111714', 'BHARAT PARENTERALS, INDIA', 'PARIL 5', '(enalapril maleate 5 mg) tablet, 1 tablet', 'BHARAT PARENTERALS, INDIA', 'ACTIVE'),
('TMT', '147745', 'TEVA, CZECH', 'EMTHEXATE', '(methotrexate 2.5 mg) tablet, 1 tablet', 'TEVA, CZECH', 'ACTIVE'),
('TMT', '1038810', 'NOVARTIS SINGAPORE PHARMACEUTICAL MANUFACTURING, SINGAPORE', 'ENTRESTO', '(sacubitril 24.3 mg + valsartan 25.7 mg) film-coated tablet, 1 tablet', 'NOVARTIS SINGAPORE PHARMACEUTICAL MANUFACTURING, SINGAPORE', 'ACTIVE'),
('TMT', '809286', 'INJECTION 10 MG/ML', 'RESCUVOLIN', '(TEVA PHARMACEUTICAL WORKS, HUNGARY) (folinic acid 300 mg/30 mL) solution for injection, 30 mL vial', 'TEVA PHARMACEUTICAL WORKS, HUNGARY', 'ACTIVE'),
('TMT', '846478', 'เยนเนอร์ราลดรั๊กส์เฮ้าส์', 'GENAVIT', '(cyanocobalamin 1 mg/1 mL + pyridoxine 50 mg/1 mL + thiamine 100 mg/1 mL) solution for injection, 2 ', 'เยนเนอร์ราลดรั๊กส์เฮ้าส์', 'ACTIVE'),
('TMT', '269279', 'ไบร์วู๊ดฟาร์มาซูติคอล', 'BRYROCIN LOZENGES', '(benzocaine 5 mg + tyrothricin 2 mg) lozenge, 1 lozenge', 'ไบร์วู๊ดฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '943813', 'PFIZER MANUFACTURING DEUTSCHLAND, GERMANY', 'XELJANZ', '(tofacitinib 5 mg) film-coated tablet, 1 tablet', 'PFIZER MANUFACTURING DEUTSCHLAND, GERMANY', 'ACTIVE'),
('TMT', '914790', 'F 10669', 'UREA 20% CREAM', '(urea 20 g/100 g) cream, 30 g jar', 'โรงพยาบาลสรรพสิทธิประสงค์', 'ACTIVE'),
('TMT', '107553', 'LILLY PHARMA, GERMANY', 'XIGRIS', '(activated protein c, recombinant human 20 mg) powder for solution for injection, 1 vial', 'LILLY PHARMA, GERMANY', 'ACTIVE'),
('TMT', '330237', 'สยามเมดิแคร์', 'FORCYCLINE', '(tetracycline 250 mg) capsule, hard, 1 capsule', 'สยามเมดิแคร์', 'ACTIVE'),
('TMT', '136936', 'OSG NORWICH, U.S.A.', 'ACTONEL', '(risedronate sodium 30 mg) film-coated tablet, 1 tablet', 'OSG NORWICH, U.S.A.', 'ACTIVE'),
('TMT', '1299351', 'LINCOLN PHARMACEUTICALS, INDIA', 'GASTRO-RESISTANT SODIUM VALPROATE TABLETS', '(valproate sodium 200 mg) gastro-resistant tablet, 1 tablet', 'LINCOLN PHARMACEUTICALS, INDIA', 'ACTIVE'),
('TMT', '400641', 'SIPHARM SISSELN, SWITZERLAND', 'P Z A', '(pyrazinamide 500 mg) tablet, 1 tablet', 'SIPHARM SISSELN, SWITZERLAND', 'ACTIVE'),
('TMT', '365053', 'เอช.เค.ฟาร์มาซูติคอล', 'MACOL', '(orphenadrine citrate 30 mg + paracetamol 500 mg) tablet, 1 tablet', 'เอช.เค.ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '118943', 'เวสโก ฟาร์มาซูติคอล', 'N-ZEN TAB', '(diclofenac sodium 25 mg) gastro-resistant tablet, 1 tablet', 'เวสโก ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '447762', 'ห้างขายยาตราเจ็ดดาว', 'STARMOL GREEN', '(paracetamol 500 mg) tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '545692', 'สยามเภสัช', 'CLARAXIM', '(cefotaxime 1 g) powder for solution for injection/infusion, 1 vial', 'สยามเภสัช', 'ACTIVE'),
('TMT', '1358860', 'CHONG KUN DANG PHARMACEUTICAL, KOREA', 'ALVONESP 30 MCG / 0.5 ML', '(darbepoetin alfa 30 mcg/0.5 mL) solution for injection, 0.5 mL prefilled syr', 'CHONG KUN DANG PHARMACEUTICAL, KOREA', 'ACTIVE'),
('TMT', '130767', 'เจริญเภสัชแล็บ', 'PAINNOX', '(mefenamic acid 250 mg) capsule, hard, 1 capsule', 'เจริญเภสัชแล็บ', 'ACTIVE'),
('TMT', '955755', 'อินแพคฟาร์มา', 'CODARIN-A', '(chlorphenamine maleate 2 mg + paracetamol 325 mg) capsule, hard, 1 capsule', 'อินแพคฟาร์มา', 'ACTIVE'),
('TMT', '327490', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'FLOCXIN 300', '(ofloxacin 300 mg) film-coated tablet, 1 tablet', 'โอสถ อินเตอร์ แลบบอราทอรีส์', 'ACTIVE'),
('TMT', '1001932', '2017', 'FLUARIX TETRA', '(GLAXOSMITHKLINE BIOLOGICALS, GERMANY) (influenza type A virus vaccine, A/Hong Kong/4801/2014 (H3N2)', 'GLAXOSMITHKLINE BIOLOGICALS, GERMANY', 'ACTIVE'),
('TMT', '1287325', 'TORRENT PHARMACEUTICALS, INDIA', 'LAMITOR-50', '(lamotrigine 50 mg) tablet, 1 tablet', 'TORRENT PHARMACEUTICALS, INDIA', 'ACTIVE'),
('TMT', '766317', 'INTAS PHARMACEUTICALS, INDIA', 'ZOLOTEM-20', '(temozolomide 20 mg) capsule, hard, 1 capsule', 'INTAS PHARMACEUTICALS, INDIA', 'ACTIVE'),
('TMT', '448348', 'องค์การเภสัชกรรม', 'STAVUDINE', '(stavudine 20 mg) capsule, hard, 1 capsule', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '128851', 'BOEHRINGER INGELHEIM, GERMANY', 'MOBIC', '(meloxicam 15 mg) tablet, 1 tablet', 'BOEHRINGER INGELHEIM, GERMANY', 'ACTIVE'),
('TMT', '1111858', '3 MG', 'NINLARO', 'CAPSULE (HAUPT PHARMA AMAREG, GERMANY) (ixazomib 3 mg) capsule, hard, 1 capsule', 'HAUPT PHARMA AMAREG, GERMANY', 'ACTIVE'),
('TMT', '658362', 'LILLY PHARMA, GERMANY', 'HUMULIN R', '(insulin human 100 iu/1 mL) solution for injection, 10 mL vial', 'LILLY PHARMA, GERMANY', 'ACTIVE'),
('TMT', '852405', 'ซีฟาม', 'PODINE SOLUTION', '(povidone iodine 10 g/100 mL) cutaneous solution, 15 mL bottle', 'ซีฟาม', 'ACTIVE'),
('TMT', '429848', 'ซีโนฟาร์ม', 'RIFOLD', '(rifampicin 300 mg) capsule, hard, 1 capsule', 'ซีโนฟาร์ม', 'ACTIVE'),
('TMT', '123507', 'โอลิค', 'BRUFEN 400', '(ibuprofen 400 mg) film-coated tablet, 1 tablet', 'โอลิค', 'ACTIVE'),
('TMT', '125778', 'ห้างขายยาตราเจ็ดดาว', 'TYHOFEN', '(ibuprofen 400 mg) film-coated tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '513735', 'D.P.T. LABORATORIES, PHILIPPINES', 'BACTROBAN', '(mupirocin 2 g/100 g) cream, 15 g tube', 'D.P.T. LABORATORIES, PHILIPPINES', 'ACTIVE'),
('TMT', '794128', 'CSL BEHRING, GERMANY', 'BERIRAB P', '(rabies immunoglobulin (human) 1500 iu/10 mL) solution for injection, 10 mL vial', 'CSL BEHRING, GERMANY', 'ACTIVE'),
('TMT', '827052', 'นิด้า ฟาร์มา', 'PHENICOL', '(chloramphenicol 500 mg/100 mL) eye drops, solution, 5 mL bottle', 'นิด้า ฟาร์มา', 'ACTIVE'),
('TMT', '566531', 'PRODUITS DENTAIRES PIERRE ROLLAND, FRANCE', 'XYLOROLLAND', '(epinephrine 1.25 mg/100 mL + lidocaine hydrochloride 2 g/100 mL) solution for injection, 1.8 mL car', 'PRODUITS DENTAIRES PIERRE ROLLAND, FRANCE', 'ACTIVE'),
('TMT', '281949', 'ELI LILLY, U.K.', 'CIALIS', '(tadalafil 10 mg) tablet, 1 tablet (invalid)', 'ELI LILLY, U.K.', 'ACTIVE'),
('TMT', '1004123', 'ELI LILLY AND COMPANY, U.S.A.', 'CYRAMZA', '(ramucirumab 100 mg/10 mL) concentrate for solution for infusion, 10 mL vial', 'ELI LILLY AND COMPANY, U.S.A.', 'ACTIVE'),
('TMT', '125254', 'ห้างขายยาตราเจ็ดดาว', 'CANUFEN', '(ibuprofen 400 mg) film-coated tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '316767', 'เลิศสิงห์เภสัชกรรม', 'DOMILIUM', '(domperidone 10 mg) tablet, 1 tablet', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '359432', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'LEVOPAR', '(benserazide 50 mg + levodopa 200 mg) tablet, 1 tablet', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '227779', 'แหลมทองการแพทย์', 'A-BIN', '(pyrimethamine 25 mg) tablet, 1 tablet', 'แหลมทองการแพทย์', 'ACTIVE'),
('TMT', '128912', 'ยูโทเปี้ยน', 'FEVEK', '(mefenamic acid 250 mg) film-coated tablet, 1 tablet', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '729435', 'โรงงานเภสัชกรรมเกร๊ทเตอร์ฟาร์ม่า', 'OXYMET', '(oxymetazoline hydrochloride 25 mg/100 mL) nasal drops, solution, 10 mL bottle', 'โรงงานเภสัชกรรมเกร๊ทเตอร์ฟาร์ม่า', 'ACTIVE'),
('TMT', '954989', 'อินแพคฟาร์มา', 'ERYTHROMYCIN', '(erythromycin 125 mg/5 mL) powder for oral suspension, 60 mL bottle', 'อินแพคฟาร์มา', 'ACTIVE'),
('TMT', '699429', 'อินเตอร์ไทย ฟาร์มาซูติเคิ้ล แมนูแฟคเจอริ่ง', 'Z-BEC', '(multivitamins + trace elements) coated tablet, 1 tablet', 'อินเตอร์ไทย ฟาร์มาซูติเคิ้ล แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '442659', 'ที.โอ. ฟาร์ม่า', 'SIMCONE-T SUGAR FREE', '(simeticone 80 mg) chewable tablet, 1 tablet', 'ที.โอ. ฟาร์ม่า', 'ACTIVE'),
('TMT', '367833', 'แหลมทองการแพทย์', 'MARZOLAM 0.5', '(alprazolam 500 mcg) tablet, 1 tablet', 'แหลมทองการแพทย์', 'ACTIVE'),
('TMT', '1250015', 'POWDER FOR SOLUTION FOR INFUSION', 'VORICONAZOLE TEVA', '(PLIVA CROATIA, CROATIA) (voriconazole 200 mg) powder for solution for infusion, 1 vial', 'PLIVA CROATIA, CROATIA', 'ACTIVE'),
('TMT', '442732', 'เมดิแคป', 'SIMETHICONE', '(simeticone 200 mg) capsule, soft, 1 capsule', 'เมดิแคป', 'ACTIVE'),
('TMT', '1306629', '5 MG CHEWABLE TABLET', 'MULOZ', '(สยามเภสัช) (montelukast 5 mg) chewable tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '1186739', 'โปลิฟาร์ม', 'LEVANTE 500', '(levetiracetam 500 mg) film-coated tablet, 1 tablet', 'โปลิฟาร์ม', 'ACTIVE'),
('TMT', '144181', 'ONCOTEC PHARMA, GERMANY', 'DACARBAZINE MEDAC', '(dacarbazine 500 mg) powder for solution for infusion, 1 vial', 'ONCOTEC PHARMA, GERMANY', 'ACTIVE'),
('TMT', '150019', 'KOREA UNITED PHARM, KOREA', 'UNITORAL', '(tegafur 100 mg + uracil 224 mg) capsule, hard, 1 capsule', 'KOREA UNITED PHARM, KOREA', 'ACTIVE'),
('TMT', '724120', 'KEDRION, ITALY', 'AIMAFIX', '(nonacog alfa 500 iu) powder for solution for injection, 1 vial', 'KEDRION, ITALY', 'ACTIVE'),
('TMT', '1004422', 'วิทยาศรม (สาขา 2', 'SULPHUR', ') (sulfur 10 g/100 g) ointment, 15 g tube', 'วิทยาศรม (สาขา 2)', 'ACTIVE'),
('TMT', '717045', 'บางกอกแล็ป แอนด์ คอสเมติค', 'PLAIVANA', '(น้ำมันไพล 14 g/100 g) cream, 35 g tube (invalid)', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '344600', 'เจริญเภสัชแล็บ', 'HIPPRO FORTE', '(ciprofloxacin 500 mg) film-coated tablet, 1 tablet', 'เจริญเภสัชแล็บ', 'ACTIVE'),
('TMT', '619537', 'พาตาร์แลบ', 'ANTIWORM', '(mebendazole 100 mg/5 mL) oral suspension, 30 mL bottle', 'พาตาร์แลบ', 'ACTIVE'),
('TMT', '332516', 'สยามเมดิแคร์', 'FUNGIVIN 500', '(griseofulvin 500 mg) tablet, 1 tablet', 'สยามเมดิแคร์', 'ACTIVE'),
('TMT', '924246', 'F 12249', 'SA 10% IN TA CREAM', '(salicylic acid 10 g/100 g + triamcinolone acetonide 20 mg/100 g) cream, 500 g jar', 'สถาบันโรคผิวหนัง', 'ACTIVE'),
('TMT', '322465', 'ABBOTT LABORATORIES, U.S.A.', 'ERY-TAB', '(erythromycin 125 mg) gastro-resistant tablet, 1 tablet', 'ABBOTT LABORATORIES, U.S.A.', 'ACTIVE'),
('TMT', '582448', 'ห้างขายยาตราเจ็ดดาว', 'FATEL', '(albendazole 100 mg/5 mL) oral suspension, 20 mL bottle', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '331533', 'ไบร์วู๊ดฟาร์มาซูติคอล', 'FROSSY', '(chlorphenamine maleate 4 mg + paracetamol 500 mg + phenylephrine hydrochloride 10 mg) coated tablet', 'ไบร์วู๊ดฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '104017', 'ยูนีซัน', 'FAMOMED 40', '(famotidine 40 mg) film-coated tablet, 1 tablet', 'ยูนีซัน', 'ACTIVE'),
('TMT', '411355', 'วี.เอส. ฟาร์ม่า (1971', 'PINTAB', ') (orphenadrine citrate 35 mg + paracetamol 450 mg) tablet, 1 tablet', 'วี.เอส. ฟาร์ม่า (1971)', 'ACTIVE'),
('TMT', '142696', 'PFIZER (PERTH', 'CARBOPLATIN', ', AUSTRALIA) (carboplatin 50 mg/5 mL) concentrate for solution for infusion, 5 mL vial', 'PFIZER (PERTH), AUSTRALIA', 'ACTIVE'),
('TMT', '600577', 'เลิศสิงห์เภสัชกรรม', 'COLAXIN-G', '(cefalexin 125 mg/5 mL) powder for syrup, 60 mL bottle', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '117251', 'ZIMVA', 'SIMVASTATIN', '(องค์การเภสัชกรรม) (simvastatin 10 mg) film-coated tablet, 1 tablet (invalid)', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '346544', 'พอนด์ เคมีคอล', 'HYFLOX', '(ofloxacin 100 mg) film-coated tablet, 1 tablet', 'พอนด์ เคมีคอล', 'ACTIVE'),
('TMT', '600633', 'เลิศสิงห์เภสัชกรรม', 'COLAXIN-Y', '(cefalexin 125 mg/5 mL) powder for syrup, 60 mL bottle', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '1204471', 'FRESENIUS MEDICAL CARE PRODUCTION, MALAYSIA', 'CAPD/DPCA 4 ANDY DISC LINK', '(calcium chloride dihydrate 25.73 mg/100 mL + dextrose 2.273 g/100 mL + magnesium chloride hexahydra', 'FRESENIUS MEDICAL CARE PRODUCTION, MALAYSIA', 'ACTIVE'),
('TMT', '801533', 'BAXTER HEALTHCARE PHILS, PHILIPPINES', '0.9% SODIUM CHLORIDE', '(sodium chloride 900 mg/100 mL) solution for infusion, 1 L bag', 'BAXTER HEALTHCARE PHILS, PHILIPPINES', 'ACTIVE'),
('TMT', '410817', 'เอช.เค.ฟาร์มาซูติคอล', 'PILOTOL', '(glipizide 5 mg) tablet, 1 tablet', 'เอช.เค.ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '901634', 'F 12262', 'SODIUM NITRATE', '(sodium nitrate 500 mg/100 mL) gargle/mouthwash, 240 mL bottle', 'สถาบันธัญญารักษ์', 'ACTIVE'),
('TMT', '535280', 'JANSSEN PHARMACEUTICA, BELGIUM', 'DUROGESIC', '(fentanyl 12 mcg/1 hr) transdermal patch, 2.1 mg patch', 'JANSSEN PHARMACEUTICA, BELGIUM', 'ACTIVE'),
('TMT', '134790', 'นิวยอร์ค เคมีเกิ้ล', 'NUTARZOL', '(piroxicam 10 mg) capsule, hard, 1 capsule', 'นิวยอร์ค เคมีเกิ้ล', 'ACTIVE'),
('TMT', '518369', 'PFIZER, KOREA', 'TROSYD', '(tioconazole 1 g/100 g) cream, 15 g tube', 'PFIZER, KOREA', 'ACTIVE'),
('TMT', '1033944', 'ห้างขายยาตราเจ็ดดาว', 'SANOCLOX', '(cloxacillin 500 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '1125099', 'ที.แมน ฟาร์มา', 'ACVIT-A', '(tretinoin 50 mg/100 g) gel, 500 g jar', 'ที.แมน ฟาร์มา', 'ACTIVE'),
('TMT', '952421', 'FAMAR HEALTH CARE SERVICES MADRID, SPAIN', 'ISOPTIN', '(verapamil hydrochloride 5 mg/2 mL) solution for injection, 2 mL ampoule', 'FAMAR HEALTH CARE SERVICES MADRID, SPAIN', 'ACTIVE'),
('TMT', '1031522', 'ที.โอ. เคมีคอลส์ (1979', 'TOPRELIN 25', '(กรุงเทพฯ)) (pregabalin 25 mg) capsule, hard, 1 capsule', 'ที.โอ. เคมีคอลส์ (1979) (กรุงเทพฯ)', 'ACTIVE'),
('TMT', '1006131', 'JANSSEN PHARMACEUTICA, BELGIUM', 'INVEGA SUSTENNA', '(paliperidone 50 mg/0.5 mL) prolonged-release suspension for injection, 0.5 mL prefilled syr', 'JANSSEN PHARMACEUTICA, BELGIUM', 'ACTIVE'),
('TMT', '557634', 'เอ.เอ็น.บี. ลาบอราตอรี่', 'DEXTROSE 5% IN DISTILLED WATER', '(dextrose 5 g/100 mL) solution for injection/infusion, 100 mL bag', 'เอ.เอ็น.บี. ลาบอราตอรี่', 'ACTIVE'),
('TMT', '119783', 'เอส.เอส.พี. ลาบอราตอรี่', 'SINCLONAC 50', '(diclofenac sodium 50 mg) gastro-resistant tablet, 1 tablet', 'เอส.เอส.พี. ลาบอราตอรี่', 'ACTIVE'),
('TMT', '297549', 'ค็อกซ์', 'COX-DIMENHYDRINATE', '(dimenhydrinate 50 mg) tablet, 1 tablet', 'ค็อกซ์', 'ACTIVE'),
('TMT', '1317249', 'INVENTIA HEALTHCARE, INDIA', 'NEUROFAX SR 75', '(venlafaxine 75 mg) prolonged-release capsule, hard, 1 capsule', 'INVENTIA HEALTHCARE, INDIA', 'ACTIVE'),
('TMT', '595000', 'ที.โอ. เมด', 'DITAP INFANT DROPS', '(brompheniramine maleate 800 mcg/1 mL + phenylephrine hydrochloride 1 mg/1 mL) oral drops, solution,', 'ที.โอ. เมด', 'ACTIVE'),
('TMT', '908528', 'PFIZER MANUFACTURING DEUTSCHLAND, GERMANY', 'LYRICA', '(pregabalin 50 mg) capsule, hard, 1 capsule', 'PFIZER MANUFACTURING DEUTSCHLAND, GERMANY', 'ACTIVE'),
('TMT', '136467', 'ไทยนครพัฒนา', 'TORRENT', '(tenoxicam 20 mg) tablet, 1 tablet', 'ไทยนครพัฒนา', 'ACTIVE'),
('TMT', '823476', 'ที.โอ. เคมีคอลส์ (1979', 'BETOSALIC', '(กรุงเทพฯ)) (betamethasone valerate 100 mg/100 g + salicylic acid 3 g/100 g) ointment, 5 g tube', 'ที.โอ. เคมีคอลส์ (1979) (กรุงเทพฯ)', 'ACTIVE'),
('TMT', '242996', 'แลชแมน', 'AMPICILLIN', '(ampicillin 250 mg) capsule, hard, 1 capsule', 'แลชแมน', 'ACTIVE'),
('TMT', '318824', 'ห้างขายยาตราเจ็ดดาว', 'DROZINE 10', '(hydroxyzine hydrochloride 10 mg) tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '746324', 'ห้างขายยาตราเจ็ดดาว', 'NEOCLID', '(ticlopidine hydrochloride 250 mg) film-coated tablet, 1 tablet (invalid)', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '1156982', 'แมคโครฟาร์', 'C-MOX 500', '(amoxicillin 500 mg) capsule, hard, 1 capsule', 'แมคโครฟาร์', 'ACTIVE'),
('TMT', '422929', 'เคมีภัณฑ์ เมดิคอล', 'RADALAX', '(niclosamide 500 mg) tablet, 1 tablet', 'เคมีภัณฑ์ เมดิคอล', 'ACTIVE'),
('TMT', '666322', 'TEVA PHARMA, JAPAN', 'NESP', '(darbepoetin alfa 20 mcg/1 mL) solution for injection, 1 mL prefilled syr', 'TEVA PHARMA, JAPAN', 'ACTIVE'),
('TMT', '539729', 'P.T. MEIJI PHARMACEUTICAL INDUSTRIES, INDONESIA', 'VICCILLIN', '(ampicillin 500 mg) powder for solution for injection, 1 vial', 'P.T. MEIJI PHARMACEUTICAL INDUSTRIES, INDONESIA', 'ACTIVE'),
('TMT', '541929', 'สามัคคีเภสัช', 'MUCOLA', '(bromhexine hydrochloride 2 mg/1 mL) solution for injection, 2 mL ampoule', 'สามัคคีเภสัช', 'ACTIVE'),
('TMT', '587690', 'เยาวราช', 'AMOXYCILLIN', '(amoxicillin 250 mg/5 mL) powder for oral suspension, 60 mL bottle', 'เยาวราช', 'ACTIVE'),
('TMT', '146131', 'BIONATIVE, SWEDEN', 'INTERFERON ALFANATIVE', '(interferon alpha 6 unit/1 mL) solution for injection, 1 mL vial', 'BIONATIVE, SWEDEN', 'ACTIVE'),
('TMT', '332776', 'เลิศสิงห์เภสัชกรรม', 'FURLIN', '(paracetamol 325 mg) tablet, 1 tablet', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '707101', 'F 13814', 'MANDL''S PAINT', '(iodine 1.25 g/100 mL + potassium iodide 2.5 g/100 mL) oromucosal solution, 30 mL bottle', 'โรงพยาบาลศิริราช', 'ACTIVE'),
('TMT', '712233', 'พี.พี. แลบอราตอรี่ส์', 'ACETAPYRIN C', '(ascorbic acid 50 mg/5 mL + chlorphenamine maleate 2 mg/5 mL + paracetamol 120 mg/5 mL) syrup (inval', 'พี.พี. แลบอราตอรี่ส์', 'ACTIVE'),
('TMT', '561688', 'เวสโก ฟาร์มาซูติคอล', 'PHENOKINON-F', '(estradiol benzoate 5 mg/1 mL + progesterone 50 mg/1 mL) solution for injection, 1 mL ampoule', 'เวสโก ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '116665', 'บางกอกแล็ป แอนด์ คอสเมติค', 'LOPIMEX', '(gemfibrozil 300 mg) capsule, hard, 1 capsule', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '289162', 'อาร์เอ็กซ์ แมนูแฟคเจอริ่ง', 'CLOXACILLIN RX 250', '(cloxacillin 250 mg) capsule, hard, 1 capsule', 'อาร์เอ็กซ์ แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '625670', 'แอตแลนติค', 'VACOLD-C', '(ascorbic acid 25 mg/5 mL + chlorphenamine maleate 1 mg/5 mL + paracetamol 120 mg/5 mL) syrup, 60 mL', 'แอตแลนติค', 'ACTIVE'),
('TMT', '745320', 'โมเดิร์น ฟาร์มา', 'ITRAZOLE', '(itraconazole 100 mg) capsule, hard, 1 capsule', 'โมเดิร์น ฟาร์มา', 'ACTIVE'),
('TMT', '121363', 'ห้างขายยาตราเจ็ดดาว', 'COSAMAX', '(glucosamine sulfate 500 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '590804', 'โอลัน-เคมเมด', 'KEMPICIN', '(ampicillin 125 mg/5 mL) powder for syrup, 60 mL bottle', 'โอลัน-เคมเมด', 'ACTIVE'),
('TMT', '242711', 'สหการโอสถ', 'AMPI 250 FRX', '(ampicillin 250 mg) capsule, hard, 1 capsule', 'สหการโอสถ', 'ACTIVE'),
('TMT', '1315169', 'F 10700', '0.12% CHLORHEXIDINE MOUTH WASH 1000 ML', '(chlorhexidine gluconate 120 mg/100 mL) gargle/mouthwash, 1 L gallon', 'โรงพยาบาลศรีสะเกษ', 'ACTIVE'),
('TMT', '253986', 'นิด้า ฟาร์มา', 'ATENOLOL-NIDA', '(atenolol 25 mg) film-coated tablet, 1 tablet', 'นิด้า ฟาร์มา', 'ACTIVE'),
('TMT', '126156', 'เภสัชกรรมศรีประสิทธิ์', 'BORAKID', '(ibuprofen 100 mg/5 mL) oral suspension, 60 mL bottle', 'เภสัชกรรมศรีประสิทธิ์', 'ACTIVE'),
('TMT', '926458', 'F 10667', 'SPECIAL MOUTHWASH DILUTED', '(chloroxylenol 16 g/100 mL) gargle/mouthwash, 4.5 L gallon', 'โรงพยาบาลบุรีรัมย์', 'ACTIVE'),
('TMT', '631812', 'ซีโนฟาร์ม', 'SANTA', '(paracetamol 120 mg/5 mL) syrup, 60 mL bottle', 'ซีโนฟาร์ม', 'ACTIVE'),
('TMT', '807453', 'เอ.เอ็น.บี. ลาบอราตอรี่', 'ISOTONIC SODIUM CHLORIDE', '(sodium chloride 900 mg/100 mL) solution for infusion, 1 L bag', 'เอ.เอ็น.บี. ลาบอราตอรี่', 'ACTIVE'),
('TMT', '1156035', 'M 10723', 'SILDENAFIL', '(sildenafil 2 mg/1 mL) oral suspension, 50 mL bottle', 'โรงพยาบาลแม่สอด', 'ACTIVE'),
('TMT', '130535', 'เกร๊ทเตอร์ฟาร์ม่า', 'MEFENAN', '(mefenamic acid 250 mg) capsule, hard, 1 capsule', 'เกร๊ทเตอร์ฟาร์ม่า', 'ACTIVE'),
('TMT', '1252762', 'TABLETS 5 MG/1000 MG', 'XIGDUO XR', '(ASTRAZENECA PHARMACEUTICALS, U.S.A.) (dapagliflozin 5 mg + metformin hydrochloride 1 g) prolonged-r', 'ASTRAZENECA PHARMACEUTICALS, U.S.A.', 'ACTIVE'),
('TMT', '702051', 'F 13814', 'UREA IN TRIAMCINOLONE', '(triamcinolone acetonide 100 mg/100 g + urea 20 g/100 g) cream, 500 g jar', 'โรงพยาบาลศิริราช', 'ACTIVE'),
('TMT', '459676', 'สหแพทย์เภสัช', 'TIZANIDE 2', '(tizanidine 2 mg) tablet, 1 tablet', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '773967', 'F 13814', 'MAGNESIUM CHLORIDE', '(magnesium chloride 5 g/100 mL) oral solution, 100 mL bottle', 'โรงพยาบาลศิริราช', 'ACTIVE'),
('TMT', '973285', 'ห้างขายยาตราเสือดาว', 'LEOPOVIDONE', '(povidone iodine 10 g/100 g) gel, 10 g tube', 'ห้างขายยาตราเสือดาว', 'ACTIVE'),
('TMT', '350393', 'แอตแลนติค', 'ISONIAZID', '(isoniazid 300 mg) tablet, 1 tablet', 'แอตแลนติค', 'ACTIVE'),
('TMT', '1200902', 'วี.เอส. ฟาร์ม่า (1971', 'AVOMIT-M', ') (domperidone 10 mg) tablet, 1 tablet', 'วี.เอส. ฟาร์ม่า (1971)', 'ACTIVE'),
('TMT', '1135488', 'วิทยาศรม (สาขา 2', 'น้ำมันละหุ่งหวาน', ') (alcohol 0.45 mL/15 mL + amyl acetate 37 mg/15 mL + castor oil 14.507 mL/15 mL + saccharin 6 mg/15', 'วิทยาศรม (สาขา 2)', 'ACTIVE'),
('TMT', '115774', 'ยูเมด้า', 'G.F.B.-600', '(gemfibrozil 600 mg) film-coated tablet, 1 tablet', 'ยูเมด้า', 'ACTIVE'),
('TMT', '339422', 'องค์การเภสัชกรรม', 'GPO-A-FLU', '(oseltamivir 75 mg) capsule, hard, 1 capsule', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '1172010', 'ฟาร์ม่า อินโนวา', '0.9% SODIUM CHLORIDE NSS', '(sodium chloride 900 mg/100 mL) solution for injection, 10 mL prefilled syr', 'ฟาร์ม่า อินโนวา', 'ACTIVE'),
('TMT', '435161', 'พอนด์ เคมีคอล', 'R-XITHONE', '(roxithromycin 150 mg) film-coated tablet, 1 tablet', 'พอนด์ เคมีคอล', 'ACTIVE'),
('TMT', '866026', 'เบสซี่แอรอน', 'NEW GEL', '(aluminium hydroxide 2.15 g/5 mL) oral suspension, 120 mL bottle', 'เบสซี่แอรอน', 'ACTIVE'),
('TMT', '581144', 'HARSON LABORATORIES, INDIA', 'TRAMACHE', '(tramadol hydrochloride 50 mg/1 mL) solution for injection, 1 mL ampoule', 'HARSON LABORATORIES, INDIA', 'ACTIVE'),
('TMT', '404497', 'ฮีโร่มัยซิน ฟาร์ม่า', 'PARACETAMOL', '(paracetamol 500 mg) tablet, 1 tablet', 'ฮีโร่มัยซิน ฟาร์ม่า', 'ACTIVE'),
('TMT', '930396', 'TRICHEMA, SWITZERLAND', 'PERSKINDOL CLASSIC', '(bergamot oil 100 mg/100 mL + lavender oil 20 mg/100 mL + lemon oil 100 mg/100 mL + menthol 1.5 g/10', 'TRICHEMA, SWITZERLAND', 'ACTIVE'),
('TMT', '105282', 'MINAKEM DUNKERQUE, SWEDEN', 'LOSEC', '(omeprazole 40 mg) powder for solution for injection, 1 vial', 'MINAKEM DUNKERQUE, SWEDEN', 'ACTIVE'),
('TMT', '1196709', 'เอเบิ้ล เมดิคอล', 'LEQUINOX', '(levofloxacin 500 mg/100 mL) solution for infusion, 100 mL bag', 'เอเบิ้ล เมดิคอล', 'ACTIVE'),
('TMT', '763214', 'สีลมการแพทย์', 'PHENYLEPHRINE HYDROCHLORIDE', '(phenylephrine hydrochloride 10 g/100 mL) eye drops, solution, 5 mL bottle', 'สีลมการแพทย์', 'ACTIVE'),
('TMT', '649722', 'ยูนีซัน', 'SILDENAFIL', '(sildenafil 50 mg) film-coated tablet, 1 tablet', 'ยูนีซัน', 'ACTIVE'),
('TMT', '983580', 'M 10666', 'FLUCONAZOLE ED', '(fluconazole 200 mg/100 mL) eye drops, solution, 10 mL bottle', 'โรงพยาบาลมหาราชนครราชสีมา', 'ACTIVE'),
('TMT', '277603', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'CERAX 10', '(hydroxyzine hydrochloride 10 mg) film-coated tablet, 1 tablet', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '1338510', 'NOVARTIS PHARMACEUTICAL MANUFACTURING, AUSTRIA', 'HYRIMOZ HCF', '(adalimumab 20 mg/0.2 mL) solution for injection, 0.2 mL prefilled syr', 'NOVARTIS PHARMACEUTICAL MANUFACTURING, AUSTRIA', 'ACTIVE'),
('TMT', '576758', 'CHI SHENG CHEMICAL, TAIWAN', 'ANESVAN', '(propofol 200 mg/20 mL) emulsion for injection/infusion, 20 mL ampoule', 'CHI SHENG CHEMICAL, TAIWAN', 'ACTIVE'),
('TMT', '645621', 'SCHERING-PLOUGH LABS, ITALY', 'ELOMET', '(mometasone furoate 100 mg/100 g) cutaneous solution, 30 mL bottle', 'SCHERING-PLOUGH LABS, ITALY', 'ACTIVE'),
('TMT', '393145', 'ห้างขายยาตราเจ็ดดาว', 'NORFLOXACIN 400', '(norfloxacin 400 mg) film-coated tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '425893', 'GLAXO WELLCOME OPERATIONS, U.K.', 'RETROVIR', '(zidovudine 100 mg) capsule, hard, 1 capsule', 'GLAXO WELLCOME OPERATIONS, U.K.', 'ACTIVE'),
('TMT', '137062', 'สยามเภสัช', 'ZOLENNIC', '(zoledronic acid 4 mg/5 mL) concentrate for solution for infusion, 5 mL vial', 'สยามเภสัช', 'ACTIVE'),
('TMT', '697539', 'ที.พี. ดรัก แลบบอราทอรี่ส์ (พระราม 2', 'PHENDIRIDINE', ') (phenazopyridine 100 mg) coated tablet, 1 tablet', 'ที.พี. ดรัก แลบบอราทอรี่ส์ (พระราม 2)', 'ACTIVE'),
('TMT', '954744', 'ยูนีซัน', 'BAGES', '(camphor 4 g/100 g + menthol 10 g/100 g + methyl salicylate 30 g/100 g) cream, 30 g tube', 'ยูนีซัน', 'ACTIVE'),
('TMT', '741151', 'KEDRION, ITALY', 'UMAN ALBUMIN', '(human serum albumin 20 g/100 mL) solution for infusion, 50 mL vial', 'KEDRION, ITALY', 'ACTIVE'),
('TMT', '1153010', 'แอดวานซ์ ฟาร์มาซูติคอล แมนูเฟคเจอริ่ง', 'SORIVATE', '(clobetasol propionate 50 mg/100 g) cream, 450 g jar', 'แอดวานซ์ ฟาร์มาซูติคอล แมนูเฟคเจอริ่ง', 'ACTIVE'),
('TMT', '1270521', '2.5MEQ/L', 'SOFT FLOW SC LOW CALCIUM', 'PERITONEAL DIALYSIS SOLUTION WITH DEXTROSE 4.25% W/V (PERITONE HEALTH, MALAYSIA) (calcium chloride d', 'PERITONE HEALTH, MALAYSIA', 'ACTIVE'),
('TMT', '1257443', '70 MG', 'DASATINIB SANDOZ', '(REMEDICA, CYPRUS) (dasatinib 70 mg) film-coated tablet, 1 tablet', 'REMEDICA, CYPRUS', 'ACTIVE'),
('TMT', '736879', 'CENTER FOR MOLECULAR IMMUNOLOGY, CUBA', 'HEMA-PLUS 2000', '(epoetin alfa 2000 iu/1 mL) solution for injection, 1 mL vial', 'CENTER FOR MOLECULAR IMMUNOLOGY, CUBA', 'ACTIVE'),
('TMT', '471194', 'แลชแมน', 'VENAZON', '(ketoconazole 200 mg) tablet, 1 tablet', 'แลชแมน', 'ACTIVE'),
('TMT', '495618', 'ที.โอ. เคมีคอลส์ (1979', 'CANAZOL', '(กรุงเทพฯ)) (clotrimazole 1 g/100 g) cream, 5 g tube', 'ที.โอ. เคมีคอลส์ (1979) (กรุงเทพฯ)', 'ACTIVE'),
('TMT', '522011', 'ALCON-COUVREUR, BELGIUM', 'FLAREX', '(fluorometholone acetate 100 mg/100 mL) eye drops, suspension, 5 mL bottle', 'ALCON-COUVREUR, BELGIUM', 'ACTIVE'),
('TMT', '710109', 'HOSPITAL FORMULARY', 'CAMPHORATED PHENOL SOLUTION', '(camphorated phenol solution) oromucosal solution (invalid)', 'HOSPITAL FORMULARY', 'ACTIVE'),
('TMT', '1242031', 'อินแพคฟาร์มา', 'PARACE BLUE', '(paracetamol 500 mg) tablet, 1 tablet', 'อินแพคฟาร์มา', 'ACTIVE'),
('TMT', '148918', 'F. HOFFMANN-LA ROCHE, SWITZERLAND', 'PEGLASTA', '(pegfilgrastim 10 mg/1 mL) solution for injection, 1 mL prefilled syr', 'F. HOFFMANN-LA ROCHE, SWITZERLAND', 'ACTIVE'),
('TMT', '343180', 'สยามเภสัช', 'HARTSORB', '(isosorbide dinitrate 10 mg) tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '333391', 'ห้างขายยาตราเจ็ดดาว', 'FUTIXAC', '(fluoxetine 20 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '732136', 'เรกคิทท์ เบนคีเซอร์ เฮลธ์แคร์', 'STREPSILS WITH C', '(amylmetacresol 600 mcg + ascorbic acid 100 mg + dichlorobenzyl alcohol 1.2 mg) lozenge, 1 lozenge', 'เรกคิทท์ เบนคีเซอร์ เฮลธ์แคร์', 'ACTIVE'),
('TMT', '697161', 'ไบโอแลป', 'ONDANSETRON', '(ondansetron 8 mg/4 mL) solution for injection/infusion, 4 mL ampoule', 'ไบโอแลป', 'ACTIVE'),
('TMT', '324302', 'วี.เอส. ฟาร์ม่า (1971', 'EXTAHIS', ') (brompheniramine maleate 6 mg + phenylephrine hydrochloride 7.5 mg) film-coated tablet, 1 tablet', 'วี.เอส. ฟาร์ม่า (1971)', 'ACTIVE'),
('TMT', '1026260', 'มิลลิเมด', 'VOFLOX-250', '(levofloxacin 250 mg) film-coated tablet, 1 tablet', 'มิลลิเมด', 'ACTIVE'),
('TMT', '259928', 'ห้างยาไทย', 'BEMOXIN', '(amoxicillin 500 mg) capsule, hard, 1 capsule', 'ห้างยาไทย', 'ACTIVE'),
('TMT', '954548', 'SANDOZ, CANADA', 'FENTANYL', '(fentanyl 25 mcg/1 hr) transdermal patch, 4.2 mg patch (invalid)', 'SANDOZ, CANADA', 'ACTIVE'),
('TMT', '411816', 'เพรซิเดนท์ อินเตอร์ ฟาร์มา', 'PIPZOPRIM 200', '(sulfamethoxazole 200 mg + trimethoprim 40 mg) tablet, 1 tablet', 'เพรซิเดนท์ อินเตอร์ ฟาร์มา', 'ACTIVE'),
('TMT', '275421', 'FUJISAWA PHARMACEUTICAL, JAPAN', 'CEFSPAN', '(cefixime 100 mg) capsule, hard, 1 capsule', 'FUJISAWA PHARMACEUTICAL, JAPAN', 'ACTIVE'),
('TMT', '1035981', 'อันอันโอสถ', 'MERCUROCHROME', '(merbromin 2 g/100 mL) cutaneous solution, 450 mL bottle', 'อันอันโอสถ', 'ACTIVE'),
('TMT', '442254', 'BOEHRINGER INGELHEIM PHARMA, GERMANY', 'SIFROL 1.0', '(pramipexole dihydrochloride monohydrate 1 mg) tablet, 1 tablet (invalid)', 'BOEHRINGER INGELHEIM PHARMA, GERMANY', 'ACTIVE'),
('TMT', '402892', 'พอนด์ เคมีคอล', 'PARAC', '(paracetamol 500 mg) tablet, 1 tablet', 'พอนด์ เคมีคอล', 'ACTIVE'),
('TMT', '359990', 'ห้างขายยาตราเจ็ดดาว', 'LEXO', '(cefalexin 250 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '248555', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'APODIN', '(isosorbide dinitrate 10 mg) tablet, 1 tablet', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '461136', 'ไทยนครพัฒนา', 'TORRENT', '(orphenadrine citrate 35 mg + paracetamol 450 mg) tablet, 1 tablet', 'ไทยนครพัฒนา', 'ACTIVE'),
('TMT', '935839', 'F 12275', 'น้ำยาบ้วนปากอดบุหรี่', '(sodium nitrite 500 mcg/100 mL) gargle/mouthwash, 120 mL bottle', 'โรงพยาบาลสิรินธร จังหวัดขอนแก่น', 'ACTIVE'),
('TMT', '327823', 'ปรูฟฟ์', 'FLOXA', '(ciprofloxacin 500 mg) tablet, 1 tablet', 'ปรูฟฟ์', 'ACTIVE'),
('TMT', '599871', 'บางกอกแล็ป แอนด์ คอสเมติค', 'FUROZEF', '(cefuroxime 250 mg/5 mL) powder for oral suspension, 50 mL bottle', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '331859', 'ซีฟาม', 'FUDA', '(mebendazole 500 mg) tablet, 1 tablet', 'ซีฟาม', 'ACTIVE'),
('TMT', '112900', 'PFIZER MANUFACTURING DEUTSCHLAND, GERMANY', 'ACCUPRIL', '(quinapril 40 mg) film-coated tablet, 1 tablet', 'PFIZER MANUFACTURING DEUTSCHLAND, GERMANY', 'ACTIVE'),
('TMT', '1260507', 'F 10666', 'UREA CREAM 10% 10 GM', '(urea 10 g/100 g) cream, 10 g jar', 'โรงพยาบาลมหาราชนครราชสีมา', 'ACTIVE'),
('TMT', '284886', 'ห้างขายยาตราเจ็ดดาว', 'CIPROXEL 250', '(ciprofloxacin 250 mg) film-coated tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '404552', 'อินแพคฟาร์มา', 'PARACETAMOL 325', '(paracetamol 325 mg) tablet, 1 tablet', 'อินแพคฟาร์มา', 'ACTIVE'),
('TMT', '810953', 'ABBVIE DEUTSCHLAND, GERMANY', 'ALUVIA', '(lopinavir 100 mg + ritonavir 25 mg) film-coated tablet, 1 tablet', 'ABBVIE DEUTSCHLAND, GERMANY', 'ACTIVE'),
('TMT', '577618', 'องค์การเภสัชกรรม', 'QUININE', '(quinine dihydrochloride 600 mg/2 mL) solution for injection/infusion, 2 mL ampoule', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '482989', 'เพรซิเดนท์ อินเตอร์ ฟาร์มา', 'ZOPRIM PIP 400', '(sulfamethoxazole 400 mg + trimethoprim 80 mg) tablet, 1 tablet', 'เพรซิเดนท์ อินเตอร์ ฟาร์มา', 'ACTIVE'),
('TMT', '979355', 'PT. BIO FARMA, INDONESIA', 'MEASLES VACCINE', '(measle virus, live attenuated (CAM-70) 1000 ccid50) powder and solvent for suspension for injection', 'PT. BIO FARMA, INDONESIA', 'ACTIVE'),
('TMT', '1031757', 'โรงงานเภสัชอุตสาหกรรม เจเอสพี', 'PHARMAHOF 8 VITA WITH LYSINE', '(calcium pantothenate 5 mg/5 mL + cyanocobalamin 5 mcg/5 mL + doxercalciferol 200 iu/5 mL + lysine h', 'โรงงานเภสัชอุตสาหกรรม เจเอสพี', 'ACTIVE'),
('TMT', '477713', 'ลิวินเนอร์ ฟาร์มาซูติคอล', 'WINOPAM', '(diazepam 5 mg) tablet, 1 tablet', 'ลิวินเนอร์ ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '992554', 'JANSSEN-CILAG, ITALY', 'INTELENCE', '(etravirine 200 mg) tablet, 1 tablet', 'JANSSEN-CILAG, ITALY', 'ACTIVE'),
('TMT', '623466', 'สยามเมดิแคร์', 'COLDY', '(chlorphenamine maleate 1 mg/5 mL + paracetamol 120 mg/5 mL) syrup, 60 mL bottle', 'สยามเมดิแคร์', 'ACTIVE'),
('TMT', '1129125', 'เอ.เอ็น.บี. ลาบอราตอรี่', 'KLEAN & KARE SALINE', '(sodium chloride 900 mg/100 mL) irrigation solution, 100 mL bottle', 'เอ.เอ็น.บี. ลาบอราตอรี่', 'ACTIVE'),
('TMT', '767947', 'องค์การเภสัชกรรม', 'LEVOFLOX GPO', '(levofloxacin 500 mg) film-coated tablet, 1 tablet', 'องค์การเภสัชกรรม', 'ACTIVE'),
('TMT', '283830', 'INDOCO REMEDIES, INDIA', 'CIPRIND', '(ciprofloxacin 250 mg) film-coated tablet, 1 tablet', 'INDOCO REMEDIES, INDIA', 'ACTIVE'),
('TMT', '146532', 'AVENTIS PHARMA, U.K.', 'CAMPTO', '(irinotecan hydrochloride trihydrate 40 mg/2 mL) concentrate for solution for infusion, 2 mL vial', 'AVENTIS PHARMA, U.K.', 'ACTIVE'),
('TMT', '748745', 'พาตาร์แลบ', 'PATARVIT', '(ascorbic acid 15 mg + colecalciferol 400 iu + cyanocobalamin 10 mcg + nicotinamide 10 mg + pyridoxi', 'พาตาร์แลบ', 'ACTIVE'),
('TMT', '1052799', 'อังกฤษตรางู', 'ULCERID ORAL PASTE', '(triamcinolone acetonide 100 mg/100 g) oromucosal paste, 5 g tube', 'อังกฤษตรางู', 'ACTIVE'),
('TMT', '253550', 'ไบโอแลป', 'ATD-20', '(fluoxetine 20 mg) capsule, hard, 1 capsule', 'ไบโอแลป', 'ACTIVE'),
('TMT', '803667', 'HOSPIRA, AUSTRALIA', 'CISPLATIN', '(cisplatin 100 mg/100 mL) solution for infusion, 100 mL vial', 'HOSPIRA, AUSTRALIA', 'ACTIVE'),
('TMT', '146668', 'DABUR PHARMA, INDIA', 'IRINOTEL', '(irinotecan hydrochloride trihydrate 40 mg/2 mL) concentrate for solution for infusion, 2 mL vial', 'DABUR PHARMA, INDIA', 'ACTIVE'),
('TMT', '416721', 'เอเชี่ยน ฟาร์มาซูติคอล', 'PREDNISOLONE TABLETS', '(prednisolone 5 mg) tablet, 1 tablet', 'เอเชี่ยน ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '1300825', 'F. HOFFMANN-LA ROCHE, SWITZERLAND AND ROCHE DIAGNOSTICS, GERMANY', 'OCREVUS', '(ocrelizumab 300 mg/10 mL) concentrate for solution for infusion, 10 mL vial', 'F. HOFFMANN-LA ROCHE, SWITZERLAND AND ROCHE DIAGNOSTICS, GERMANY', 'ACTIVE'),
('TMT', '122331', 'WYETH-AYERST, U.S.A.', 'ADVIL', '(ibuprofen 200 mg) coated tablet, 1 tablet', 'WYETH-AYERST, U.S.A.', 'ACTIVE'),
('TMT', '1112687', 'LABORATOIRE AGUETTANT, FRANCE', 'NORADRENALINE AGUETTANT', '(norepinephrine 8 mg/8 mL) concentrate for solution for infusion, 8 mL ampoule', 'LABORATOIRE AGUETTANT, FRANCE', 'ACTIVE'),
('TMT', '591680', 'เมดิซีน โปรดักส์', 'ASOVON', '(bromhexine hydrochloride 4 mg/5 mL) syrup, 3.8 L bottle', 'เมดิซีน โปรดักส์', 'ACTIVE'),
('TMT', '618510', 'GLAXOSMITHKLINE, AUSTRALIA', 'EPIVIR', '(lamivudine 10 mg/1 mL) syrup, 240 mL bottle', 'GLAXOSMITHKLINE, AUSTRALIA', 'ACTIVE'),
('TMT', '836014', 'UNIQUE PHARMACEUTICAL LABORATORIES, INDIA', 'THIOPEN', '(thiopental sodium 500 mg) powder for solution for injection, 1 vial', 'UNIQUE PHARMACEUTICAL LABORATORIES, INDIA', 'ACTIVE'),
('TMT', '708819', 'F 13814', 'SHOHL''S SOLUTION', '(citric acid 10 g/100 mL + sodium citrate 9.8 g/100 mL) oral solution, 300 mL bottle', 'โรงพยาบาลศิริราช', 'ACTIVE'),
('TMT', '1352900', 'VANTIVE MANUFACTURING, SINGAPORE', 'DIANEAL PD-2 PERITONEAL DIALYSIS SOLUTION WITH 2.5 % DEXTROSE', '(calcium chloride dihydrate 25.7 mg/100 mL + dextrose monohydrate 2.5 g/100 mL + magnesium chloride ', 'VANTIVE MANUFACTURING, SINGAPORE', 'ACTIVE'),
('TMT', '377952', 'LABORATORIO ITALIANO BIOCHIMICO FARMACEUTICO LISAPHARMA, ITALY', 'MILLIBAR', '(indapamide 2.5 mg) capsule, hard, 1 capsule', 'LABORATORIO ITALIANO BIOCHIMICO FARMACEUTICO LISAPHARMA, ITALY', 'ACTIVE'),
('TMT', '373493', 'CHINA OTSUKA PHARMACEUTICAL, CHINA', 'MEPTIN', '(procaterol 50 mcg) tablet, 1 tablet', 'CHINA OTSUKA PHARMACEUTICAL, CHINA', 'ACTIVE'),
('TMT', '998666', 'F 10747', 'KCL ELIXIR 10%', '(potassium chloride 10 g/100 mL) oral solution, 60 mL bottle', 'โรงพยาบาลพัทลุง', 'ACTIVE'),
('TMT', '455248', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'TETALIN', '(atenolol 100 mg) film-coated tablet, 1 tablet', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '380277', 'SUN PHARMACEUTICAL, INDIA', 'MONOTRATE OD', '(isosorbide mononitrate 50 mg) prolonged-release tablet, 1 tablet', 'SUN PHARMACEUTICAL, INDIA', 'ACTIVE'),
('TMT', '123825', 'ยูโทเปี้ยน', 'I BRO 400', '(ibuprofen 400 mg) film-coated tablet, 1 tablet', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '582760', 'SMITHKLINE BEECHAM, PHILIPPINES', 'ZENTEL', '(albendazole 200 mg/5 mL) oral suspension, 10 mL bottle', 'SMITHKLINE BEECHAM, PHILIPPINES', 'ACTIVE'),
('TMT', '386394', 'แลชแมน', 'NAPTRAX', '(tetracycline 250 mg) capsule, hard, 1 capsule', 'แลชแมน', 'ACTIVE'),
('TMT', '864517', 'ไบโอแลป', 'VALBET', '(betamethasone valerate 100 mg/100 g) cream, 15 g tube', 'ไบโอแลป', 'ACTIVE'),
('TMT', '110064', 'MEDOCHEMIE, CYPRUS', 'NERDIPINE', '(nicardipine hydrochloride 20 mg) film-coated tablet, 1 tablet', 'MEDOCHEMIE, CYPRUS', 'ACTIVE'),
('TMT', '586530', 'ห้างขายยาตราเจ็ดดาว', 'VIMENTIM', '(amoxicillin 400 mg/5 mL + clavulanic acid 57 mg/5 mL) powder for oral suspension, 70 mL bottle', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '628660', 'ห้างขายยาน่ำก๊ก', 'HYPOTEM STRAWBERRY', '(paracetamol 120 mg/5 mL) syrup, 60 mL bottle', 'ห้างขายยาน่ำก๊ก', 'ACTIVE'),
('TMT', '332674', 'สยามเภสัช', 'FURETIC', '(furosemide 40 mg) tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '1020429', 'STERI-PHARMA, U.S.A.', 'ZERBAXA', '(ceftolozane 1 g + tazobactam 500 mg) powder for concentrate for solution for infusion, 1 vial', 'STERI-PHARMA, U.S.A.', 'ACTIVE'),
('TMT', '119765', 'REMEDICA, CYPRUS', 'REMETHAN 50', '(diclofenac sodium 50 mg) gastro-resistant tablet, 1 tablet', 'REMEDICA, CYPRUS', 'ACTIVE'),
('TMT', '979567', 'F 10681', 'LCD 5% + SA 5%', '(coal tar 1 g/100 g + salicylic acid 5 g/100 g) cream, 5 g tube', 'โรงพยาบาลสุราษฎร์ธานี', 'ACTIVE'),
('TMT', '130073', 'MA', 'T.V. GIN', '(ที.แมน ฟาร์มา) (mefenamic acid 500 mg) film-coated tablet, 1 tablet', 'ที.แมน ฟาร์มา', 'ACTIVE'),
('TMT', '407118', 'โรงงานเภสัชกรรมเกร๊ทเตอร์ฟาร์ม่า', 'PEDIA-COL', '(chlorphenamine maleate 1 mg + paracetamol 300 mg) tablet, 1 tablet', 'โรงงานเภสัชกรรมเกร๊ทเตอร์ฟาร์ม่า', 'ACTIVE'),
('TMT', '546875', 'MEDOCHEMIE, CYPRUS', 'VALORAN', '(cefotaxime 500 mg) powder for solution for injection/infusion, 1 vial', 'MEDOCHEMIE, CYPRUS', 'ACTIVE'),
('TMT', '516694', 'อังกฤษตรางู', 'NEOZOLONE', '(neomycin sulfate 250 mg/100 g + prednisolone 350 mg/100 g) cream, 5 g tube', 'อังกฤษตรางู', 'ACTIVE'),
('TMT', '137247', 'สยามเภสัช', 'ULCEFATE', '(sucralfate 1 g/5 mL) oral suspension, 60 mL bottle', 'สยามเภสัช', 'ACTIVE'),
('TMT', '443052', 'เอส.เอส.พี. ลาบอราตอรี่', 'SINEFED', '(chlorphenamine maleate 4 mg + pseudoephedrine hydrochloride 60 mg) tablet, 1 tablet', 'เอส.เอส.พี. ลาบอราตอรี่', 'ACTIVE'),
('TMT', '490326', 'แสงไทยกำปะนี', 'NEO-BETASONE', '(betamethasone 100 mg/100 g + neomycin sulfate 500 mg/100 g) cream, 400 g jar', 'แสงไทยกำปะนี', 'ACTIVE'),
('TMT', '315354', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'DISTACLOR', '(cefaclor 500 mg) capsule, hard, 1 capsule', 'เอ็ม แอนด์ เอ็ช แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '431870', 'เอช.เค.ฟาร์มาซูติคอล', 'ROFACIN 450', '(rifampicin 450 mg) capsule, hard, 1 capsule', 'เอช.เค.ฟาร์มาซูติคอล', 'ACTIVE'),
('TMT', '841780', 'ZYMA, SWITZERLAND', 'VIBROCIL-S', '(dimetindene 25 mg/100 mL + phenylephrine hydrochloride 250 mg/100 mL) nasal drops, solution, 10 mL ', 'ZYMA, SWITZERLAND', 'ACTIVE'),
('TMT', '716435', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'SPASURI 200', '(flavoxate hydrochloride 200 mg) film-coated tablet, 1 tablet', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '146149', 'VIRANATIVE, SWEDEN', 'INTERFERON ALFANATIVE', '(interferon alpha 6 unit/1 mL) solution for injection, 1 mL vial', 'VIRANATIVE, SWEDEN', 'ACTIVE'),
('TMT', '1192036', 'เลิศสิงห์เภสัชกรรม', 'VOLCLONAC SPRAY', '(diclofenac diethylamine 1.16 g/100 g) cutaneous spray, solution, 60 mL bottle', 'เลิศสิงห์เภสัชกรรม', 'ACTIVE'),
('TMT', '1027461', 'MYLAN LABORATORIES, INDIA', 'LEDVIR', '(ledipasvir 90 mg + sofosbuvir 400 mg) film-coated tablet, 1 tablet', 'MYLAN LABORATORIES, INDIA', 'ACTIVE'),
('TMT', '563797', 'BAYER, KOREA', 'ULTRAVIST 300', '(iopromide 62.34 g/100 mL) solution for injection, 100 mL vial', 'BAYER, KOREA', 'ACTIVE'),
('TMT', '783369', 'สยามเภสัช', 'CAL-OS CHEW', '(calcium carbonate 500 mg) chewable tablet, 1 tablet', 'สยามเภสัช', 'ACTIVE'),
('TMT', '404855', 'เอส.ที. กรุ๊ป ฟาร์ม่า', 'PARACOL 500', '(paracetamol 500 mg) tablet, 1 tablet', 'เอส.ที. กรุ๊ป ฟาร์ม่า', 'ACTIVE'),
('TMT', '454616', 'เคนยากุ', 'TENSIDOL', '(haloperidol 10 mg) tablet, 1 tablet', 'เคนยากุ', 'ACTIVE'),
('TMT', '399532', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ORPAR', '(orphenadrine citrate 30 mg + paracetamol 500 mg) tablet, 1 tablet', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '1249275', 'อินเตอร์ ฟาร์มา', 'OPSIL-A', '(antazoline hydrochloride 50 mg/100 mL + tetryzoline hydrochloride 40 mg/100 mL) eye drops, solution', 'อินเตอร์ ฟาร์มา', 'ACTIVE'),
('TMT', '114578', 'NOVARTIS FARMACEUTICA, SPAIN', 'VALPRES', '(valsartan 160 mg) film-coated tablet, 1 tablet', 'NOVARTIS FARMACEUTICA, SPAIN', 'ACTIVE'),
('TMT', '757926', 'สหแพทย์เภสัช', 'NASALINE', '(sodium chloride 650 mg/100 mL) nasal spray, solution, 30 mL bottle', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '600452', 'บางกอกแล็ป แอนด์ คอสเมติค', 'CEPHALEX-250', '(cefalexin 250 mg/5 mL) powder for oral suspension, 60 mL bottle', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '127772', 'ห้างขายยาตราเจ็ดดาว', 'FINDO', '(indometacin 25 mg) capsule, hard, 1 capsule', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '427730', 'แอตแลนติค', 'RICINIS', '(isoniazid 300 mg + rifampicin 150 mg) film-coated tablet, 1 tablet', 'แอตแลนติค', 'ACTIVE'),
('TMT', '947664', 'ZHEJIANG HUAHAI PHARMACEUTICAL, CHINA', 'STOCRIN', '(efavirenz 200 mg) film-coated tablet, 1 tablet', 'ZHEJIANG HUAHAI PHARMACEUTICAL, CHINA', 'ACTIVE'),
('TMT', '129789', 'ห้างขายยาตราเจ็ดดาว', 'FEVIC 500', '(mefenamic acid 500 mg) film-coated tablet, 1 tablet', 'ห้างขายยาตราเจ็ดดาว', 'ACTIVE'),
('TMT', '110721', 'J.B. CHEMICALS & PHARMACEUTICALS, INDIA', 'NICARDIA-10', '(nifedipine 10 mg) capsule, soft, 1 capsule', 'J.B. CHEMICALS & PHARMACEUTICALS, INDIA', 'ACTIVE'),
('TMT', '1241745', 'ไบโอเนท-เอเชีย', 'BOOSTAGENRED', '(diphtheria toxoid 2 Lf/0.5 mL + filamentous haemagglutinin (FHA) 5 mcg/0.5 mL + recombinant pertuss', 'ไบโอเนท-เอเชีย', 'ACTIVE'),
('TMT', '496444', 'พอนด์ เคมีคอล', 'CLOTRIN', '(clotrimazole 1 g/100 g) cream, 15 g tube', 'พอนด์ เคมีคอล', 'ACTIVE'),
('TMT', '302903', 'อาร์เอ็กซ์ แมนูแฟคเจอริ่ง', 'DE GAS', '(simeticone 80 mg) chewable tablet, 1 tablet', 'อาร์เอ็กซ์ แมนูแฟคเจอริ่ง', 'ACTIVE'),
('TMT', '348930', 'โมเดิร์น ฟาร์มา', 'INGESIC', '(orphenadrine citrate 35 mg + paracetamol 450 mg) tablet, 1 tablet', 'โมเดิร์น ฟาร์มา', 'ACTIVE'),
('TMT', '456089', 'ซีโนฟาร์ม', 'TETRACYCLINE HYDROCHLORIDE', '(tetracycline 250 mg) capsule, hard, 1 capsule', 'ซีโนฟาร์ม', 'ACTIVE'),
('TMT', '265916', 'TEIJIN PHARMA, JAPAN', 'BON-ONE', '(alfacalcidol 0.25 mcg) tablet, 1 tablet', 'TEIJIN PHARMA, JAPAN', 'ACTIVE'),
('TMT', '1003143', 'LABORATORIO REIG JOFRE, SPAIN', 'ALVOLES', '(aciclovir 250 mg) powder for solution for infusion, 1 vial', 'LABORATORIO REIG JOFRE, SPAIN', 'ACTIVE'),
('TMT', '1316274', 'LG CHEM, KOREA', 'EUCEPT', '(etanercept 50 mg/1 mL) solution for injection, 1 mL prefilled pen', 'LG CHEM, KOREA', 'ACTIVE'),
('TMT', '500173', 'โอลิค', 'CALADRYL', '(calamine 8 g/100 g + diphenhydramine hydrochloride 1 g/100 g) cream, 100 g tube', 'โอลิค', 'ACTIVE'),
('TMT', '1192186', 'VERO CELL', 'COVID-19 VACCINE', ', INACTIVATED (COVILO) (BEIJING INSTITUTE OF BIOLOGICAL PRODUCTS, CHINA) (sars-cov-2 vaccine (vero c', 'BEIJING INSTITUTE OF BIOLOGICAL PRODUCTS, CHINA', 'ACTIVE'),
('TMT', '149222', 'F. HOFFMANN-LA ROCHE, SWITZERLAND', 'MABTHERA', '(rituximab 500 mg/50 mL) concentrate for solution for infusion, 1 vial (invalid)', 'F. HOFFMANN-LA ROCHE, SWITZERLAND', 'ACTIVE'),
('TMT', '911429', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ZENZERA MB1', '(mebendazole 500 mg) chewable tablet, 1 tablet', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '498174', 'บางกอกแล็ป แอนด์ คอสเมติค', 'FANGO-B', '(betamethasone 100 mg/100 g + clotrimazole 1 g/100 g) cream, 15 g tube', 'บางกอกแล็ป แอนด์ คอสเมติค', 'ACTIVE'),
('TMT', '1205352', 'F 10724', 'TAR SHAMPOO', '(coal tar 5 mL/100 mL) shampoo, 240 mL bottle', 'โรงพยาบาลสุโขทัย', 'ACTIVE'),
('TMT', '421527', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'PYRIMOL', '(paracetamol 500 mg) tablet, 1 tablet', 'ฟาร์มาสันต์แล็บบอราตอรี่ส์', 'ACTIVE'),
('TMT', '270191', 'บูรพาโอสถ', 'BUZETIN', '(bromhexine hydrochloride 8 mg) tablet, 1 tablet', 'บูรพาโอสถ', 'ACTIVE'),
('TMT', '534516', 'ALPHAPHARM, AUSTRALIA', 'ALODORM', '(nitrazepam 5 mg) tablet, 1 tablet', 'ALPHAPHARM, AUSTRALIA', 'ACTIVE'),
('TMT', '530096', 'เภสัชกรรมศรีประสิทธิ์', 'METZODIN', '(oxymetazoline hydrochloride 50 mg/100 mL) nasal spray, solution, 10 mL bottle', 'เภสัชกรรมศรีประสิทธิ์', 'ACTIVE'),
('TMT', '688708', 'SHENYANG SUNSHINE, CHINA', 'EPIAO', '(epoetin alfa 2000 iu/1 mL) solution for injection, 1 mL prefilled syr', 'SHENYANG SUNSHINE, CHINA', 'ACTIVE'),
('TMT', '690439', 'BIO SIDUS, ARGENTINA', 'HEMAX', '(epoetin alfa 4000 iu) powder and solvent for solution for injection, 1 vial', 'BIO SIDUS, ARGENTINA', 'ACTIVE'),
('TMT', '1211832', 'GENENTECH, U.S.A.', 'CASIRIVIMAB AND IMDEVIMAB', '(imdevimab 120 mg/1 mL) concentrate for solution for infusion, 2.5 mL vial', 'GENENTECH, U.S.A.', 'ACTIVE'),
('TMT', '323103', 'อังกฤษตรางู', 'EUCIPROX', '(ciprofloxacin 500 mg) film-coated tablet, 1 tablet', 'อังกฤษตรางู', 'ACTIVE'),
('TMT', '358268', 'สหแพทย์เภสัช', 'LENNOX', '(doxazosin 4 mg) tablet, 1 tablet', 'สหแพทย์เภสัช', 'ACTIVE'),
('TMT', '538038', 'โมเดอร์นแมนู', 'AKACIN', '(amikacin 250 mg/2 mL) solution for injection, 2 mL vial', 'โมเดอร์นแมนู', 'ACTIVE'),
('TMT', '466450', 'ยูโทเปี้ยน', 'U-AMOXY 250', '(amoxicillin 250 mg) capsule, hard, 1 capsule', 'ยูโทเปี้ยน', 'ACTIVE'),
('TMT', '711741', 'BROWN MIXTURE', 'MIXTURE TUSSIS', '(HOSPITAL FORMULARY) (mixture tussis (brown mixture)) oral solution (invalid) (invalid)', 'HOSPITAL FORMULARY', 'ACTIVE'),
('TMT', '1016557', 'BARD PHARMACEUTICALS, U.K.', 'TARGIN', '(naloxone hydrochloride 5 mg + oxycodone hydrochloride 10 mg) prolonged-release tablet, 1 tablet', 'BARD PHARMACEUTICALS, U.K.', 'ACTIVE'),
('TMT', '236354', 'เอเชี่ยน ฟาร์มาซูติคอล', 'ALPRAXOL', '(alprazolam 250 mcg) tablet, 1 tablet', 'เอเชี่ยน ฟาร์มาซูติคอล', 'ACTIVE');